//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace treeDiM.StackBuilder.ExcelAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("treeDiM.StackBuilder.ExcelAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case height.
        /// </summary>
        internal static string ID_CASE_HEIGHT {
            get {
                return ResourceManager.GetString("ID_CASE_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case length.
        /// </summary>
        internal static string ID_CASE_LENGTH {
            get {
                return ResourceManager.GetString("ID_CASE_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case weight.
        /// </summary>
        internal static string ID_CASE_WEIGHT {
            get {
                return ResourceManager.GetString("ID_CASE_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case width.
        /// </summary>
        internal static string ID_CASE_WIDTH {
            get {
                return ResourceManager.GetString("ID_CASE_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum pallet height.
        /// </summary>
        internal static string ID_CONSTRAINTS_PALLETMAXIHEIGHT {
            get {
                return ResourceManager.GetString("ID_CONSTRAINTS_PALLETMAXIHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum pallet weight.
        /// </summary>
        internal static string ID_CONSTRAINTS_PALLETMAXIWEIGHT {
            get {
                return ResourceManager.GetString("ID_CONSTRAINTS_PALLETMAXIWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pallet selected!.
        /// </summary>
        internal static string ID_ERROR_NOPALLETSELECTED {
            get {
                return ResourceManager.GetString("ID_ERROR_NOPALLETSELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load weight.
        /// </summary>
        internal static string ID_LOAD_WEIGHT {
            get {
                return ResourceManager.GetString("ID_LOAD_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet height.
        /// </summary>
        internal static string ID_PALLET_HEIGHT {
            get {
                return ResourceManager.GetString("ID_PALLET_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet length.
        /// </summary>
        internal static string ID_PALLET_LENGTH {
            get {
                return ResourceManager.GetString("ID_PALLET_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet weight.
        /// </summary>
        internal static string ID_PALLET_WEIGHT {
            get {
                return ResourceManager.GetString("ID_PALLET_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet width.
        /// </summary>
        internal static string ID_PALLET_WIDTH {
            get {
                return ResourceManager.GetString("ID_PALLET_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency.
        /// </summary>
        internal static string ID_RESULT_EFFICIENCY {
            get {
                return ResourceManager.GetString("ID_RESULT_EFFICIENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string ID_RESULT_IMAGE {
            get {
                return ResourceManager.GetString("ID_RESULT_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load weight.
        /// </summary>
        internal static string ID_RESULT_LOADWEIGHT {
            get {
                return ResourceManager.GetString("ID_RESULT_LOADWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of cases.
        /// </summary>
        internal static string ID_RESULT_NOCASES {
            get {
                return ResourceManager.GetString("ID_RESULT_NOCASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid solution found!.
        /// </summary>
        internal static string ID_RESULT_NOSOLUTIONFOUND {
            get {
                return ResourceManager.GetString("ID_RESULT_NOSOLUTIONFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total pallet weight.
        /// </summary>
        internal static string ID_RESULT_TOTALPALLETWEIGHT {
            get {
                return ResourceManager.GetString("ID_RESULT_TOTALPALLETWEIGHT", resourceCulture);
            }
        }
    }
}
