//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace treeDiM.StackBuilder.ExcelAddIn.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B3")]
        public string CellCaseLength {
            get {
                return ((string)(this["CellCaseLength"]));
            }
            set {
                this["CellCaseLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B4")]
        public string CellCaseWidth {
            get {
                return ((string)(this["CellCaseWidth"]));
            }
            set {
                this["CellCaseWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B5")]
        public string CellCaseHeight {
            get {
                return ((string)(this["CellCaseHeight"]));
            }
            set {
                this["CellCaseHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B6")]
        public string CellCaseWeight {
            get {
                return ((string)(this["CellCaseWeight"]));
            }
            set {
                this["CellCaseWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B17")]
        public string CellPalletLength {
            get {
                return ((string)(this["CellPalletLength"]));
            }
            set {
                this["CellPalletLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B18")]
        public string CellPalletWidth {
            get {
                return ((string)(this["CellPalletWidth"]));
            }
            set {
                this["CellPalletWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B19")]
        public string CellPalletHeight {
            get {
                return ((string)(this["CellPalletHeight"]));
            }
            set {
                this["CellPalletHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B20")]
        public string CellPalletWeight {
            get {
                return ((string)(this["CellPalletWeight"]));
            }
            set {
                this["CellPalletWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B23")]
        public string CellMaxPalletHeight {
            get {
                return ((string)(this["CellMaxPalletHeight"]));
            }
            set {
                this["CellMaxPalletHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B24")]
        public string CellMaxPalletWeight {
            get {
                return ((string)(this["CellMaxPalletWeight"]));
            }
            set {
                this["CellMaxPalletWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B27")]
        public string CellNoCases {
            get {
                return ((string)(this["CellNoCases"]));
            }
            set {
                this["CellNoCases"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B28")]
        public string CellLoadWeight {
            get {
                return ((string)(this["CellLoadWeight"]));
            }
            set {
                this["CellLoadWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B29")]
        public string CellTotalPalletWeight {
            get {
                return ((string)(this["CellTotalPalletWeight"]));
            }
            set {
                this["CellTotalPalletWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public double ImageWidth {
            get {
                return ((double)(this["ImageWidth"]));
            }
            set {
                this["ImageWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public double ImageHeight {
            get {
                return ((double)(this["ImageHeight"]));
            }
            set {
                this["ImageHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public double ImageX {
            get {
                return ((double)(this["ImageX"]));
            }
            set {
                this["ImageX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double ImageY {
            get {
                return ((double)(this["ImageY"]));
            }
            set {
                this["ImageY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ImageSize {
            get {
                return ((int)(this["ImageSize"]));
            }
            set {
                this["ImageSize"] = value;
            }
        }
    }
}
