//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace treeDiM.StackBuilder.WCFService.Test.SB_SR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCSBItem", Namespace="http://schemas.datacontract.org/2004/07/treeDiM.StackBuilder.WCFAppServ")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBPallet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBInterlayer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBBundle))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBCase))]
    public partial class DCSBItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UnitSystemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnitSystem {
            get {
                return this.UnitSystemField;
            }
            set {
                if ((this.UnitSystemField.Equals(value) != true)) {
                    this.UnitSystemField = value;
                    this.RaisePropertyChanged("UnitSystem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCSBPallet", Namespace="http://schemas.datacontract.org/2004/07/treeDiM.StackBuilder.WCFAppServ")]
    [System.SerializableAttribute()]
    public partial class DCSBPallet : treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBDim3D DimensionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PalletTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Color {
            get {
                return this.ColorField;
            }
            set {
                if ((this.ColorField.Equals(value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBDim3D Dimensions {
            get {
                return this.DimensionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DimensionsField, value) != true)) {
                    this.DimensionsField = value;
                    this.RaisePropertyChanged("Dimensions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PalletType {
            get {
                return this.PalletTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PalletTypeField, value) != true)) {
                    this.PalletTypeField = value;
                    this.RaisePropertyChanged("PalletType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCSBInterlayer", Namespace="http://schemas.datacontract.org/2004/07/treeDiM.StackBuilder.WCFAppServ")]
    [System.SerializableAttribute()]
    public partial class DCSBInterlayer : treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBDim3D DimensionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Color {
            get {
                return this.ColorField;
            }
            set {
                if ((this.ColorField.Equals(value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBDim3D Dimensions {
            get {
                return this.DimensionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DimensionsField, value) != true)) {
                    this.DimensionsField = value;
                    this.RaisePropertyChanged("Dimensions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCSBBundle", Namespace="http://schemas.datacontract.org/2004/07/treeDiM.StackBuilder.WCFAppServ")]
    [System.SerializableAttribute()]
    public partial class DCSBBundle : treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBDim3D DimensionsUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double UnitWeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Color {
            get {
                return this.ColorField;
            }
            set {
                if ((this.ColorField.Equals(value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBDim3D DimensionsUnit {
            get {
                return this.DimensionsUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.DimensionsUnitField, value) != true)) {
                    this.DimensionsUnitField = value;
                    this.RaisePropertyChanged("DimensionsUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double UnitWeight {
            get {
                return this.UnitWeightField;
            }
            set {
                if ((this.UnitWeightField.Equals(value) != true)) {
                    this.UnitWeightField = value;
                    this.RaisePropertyChanged("UnitWeight");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCSBCase", Namespace="http://schemas.datacontract.org/2004/07/treeDiM.StackBuilder.WCFAppServ")]
    [System.SerializableAttribute()]
    public partial class DCSBCase : treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ColorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBDim3D DimensionsInnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBDim3D DimensionsOuterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasInnerDimsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MaxWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> NetWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShowTapeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TapeColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TapeWidthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Colors {
            get {
                return this.ColorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorsField, value) != true)) {
                    this.ColorsField = value;
                    this.RaisePropertyChanged("Colors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBDim3D DimensionsInner {
            get {
                return this.DimensionsInnerField;
            }
            set {
                if ((object.ReferenceEquals(this.DimensionsInnerField, value) != true)) {
                    this.DimensionsInnerField = value;
                    this.RaisePropertyChanged("DimensionsInner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBDim3D DimensionsOuter {
            get {
                return this.DimensionsOuterField;
            }
            set {
                if ((object.ReferenceEquals(this.DimensionsOuterField, value) != true)) {
                    this.DimensionsOuterField = value;
                    this.RaisePropertyChanged("DimensionsOuter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasInnerDims {
            get {
                return this.HasInnerDimsField;
            }
            set {
                if ((this.HasInnerDimsField.Equals(value) != true)) {
                    this.HasInnerDimsField = value;
                    this.RaisePropertyChanged("HasInnerDims");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MaxWeight {
            get {
                return this.MaxWeightField;
            }
            set {
                if ((this.MaxWeightField.Equals(value) != true)) {
                    this.MaxWeightField = value;
                    this.RaisePropertyChanged("MaxWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> NetWeight {
            get {
                return this.NetWeightField;
            }
            set {
                if ((this.NetWeightField.Equals(value) != true)) {
                    this.NetWeightField = value;
                    this.RaisePropertyChanged("NetWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowTape {
            get {
                return this.ShowTapeField;
            }
            set {
                if ((this.ShowTapeField.Equals(value) != true)) {
                    this.ShowTapeField = value;
                    this.RaisePropertyChanged("ShowTape");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TapeColor {
            get {
                return this.TapeColorField;
            }
            set {
                if ((this.TapeColorField.Equals(value) != true)) {
                    this.TapeColorField = value;
                    this.RaisePropertyChanged("TapeColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TapeWidth {
            get {
                return this.TapeWidthField;
            }
            set {
                if ((this.TapeWidthField.Equals(value) != true)) {
                    this.TapeWidthField = value;
                    this.RaisePropertyChanged("TapeWidth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCSBDim3D", Namespace="http://schemas.datacontract.org/2004/07/treeDiM.StackBuilder.WCFAppServ")]
    [System.SerializableAttribute()]
    public partial class DCSBDim3D : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double M0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double M1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double M2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double M0 {
            get {
                return this.M0Field;
            }
            set {
                if ((this.M0Field.Equals(value) != true)) {
                    this.M0Field = value;
                    this.RaisePropertyChanged("M0");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double M1 {
            get {
                return this.M1Field;
            }
            set {
                if ((this.M1Field.Equals(value) != true)) {
                    this.M1Field = value;
                    this.RaisePropertyChanged("M1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double M2 {
            get {
                return this.M2Field;
            }
            set {
                if ((this.M2Field.Equals(value) != true)) {
                    this.M2Field = value;
                    this.RaisePropertyChanged("M2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCSBConstraintSet", Namespace="http://schemas.datacontract.org/2004/07/treeDiM.StackBuilder.WCFAppServ")]
    [System.SerializableAttribute()]
    public partial class DCSBConstraintSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintDouble MaxHeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintInt MaxNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintDouble MaxWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBBool3 OrientationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBDim2D OverhangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintDouble MaxHeight {
            get {
                return this.MaxHeightField;
            }
            set {
                if ((object.ReferenceEquals(this.MaxHeightField, value) != true)) {
                    this.MaxHeightField = value;
                    this.RaisePropertyChanged("MaxHeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintInt MaxNumber {
            get {
                return this.MaxNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MaxNumberField, value) != true)) {
                    this.MaxNumberField = value;
                    this.RaisePropertyChanged("MaxNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintDouble MaxWeight {
            get {
                return this.MaxWeightField;
            }
            set {
                if ((object.ReferenceEquals(this.MaxWeightField, value) != true)) {
                    this.MaxWeightField = value;
                    this.RaisePropertyChanged("MaxWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBBool3 Orientation {
            get {
                return this.OrientationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrientationField, value) != true)) {
                    this.OrientationField = value;
                    this.RaisePropertyChanged("Orientation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBDim2D Overhang {
            get {
                return this.OverhangField;
            }
            set {
                if ((object.ReferenceEquals(this.OverhangField, value) != true)) {
                    this.OverhangField = value;
                    this.RaisePropertyChanged("Overhang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCSBConstraintDouble", Namespace="http://schemas.datacontract.org/2004/07/treeDiM.StackBuilder.WCFAppServ")]
    [System.SerializableAttribute()]
    public partial class DCSBConstraintDouble : treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Value_dField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value_d {
            get {
                return this.Value_dField;
            }
            set {
                if ((this.Value_dField.Equals(value) != true)) {
                    this.Value_dField = value;
                    this.RaisePropertyChanged("Value_d");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCSBConstraintInt", Namespace="http://schemas.datacontract.org/2004/07/treeDiM.StackBuilder.WCFAppServ")]
    [System.SerializableAttribute()]
    public partial class DCSBConstraintInt : treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Value_iField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value_i {
            get {
                return this.Value_iField;
            }
            set {
                if ((this.Value_iField.Equals(value) != true)) {
                    this.Value_iField = value;
                    this.RaisePropertyChanged("Value_i");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCSBBool3", Namespace="http://schemas.datacontract.org/2004/07/treeDiM.StackBuilder.WCFAppServ")]
    [System.SerializableAttribute()]
    public partial class DCSBBool3 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool YField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ZField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Z {
            get {
                return this.ZField;
            }
            set {
                if ((this.ZField.Equals(value) != true)) {
                    this.ZField = value;
                    this.RaisePropertyChanged("Z");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCSBDim2D", Namespace="http://schemas.datacontract.org/2004/07/treeDiM.StackBuilder.WCFAppServ")]
    [System.SerializableAttribute()]
    public partial class DCSBDim2D : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double M0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double M1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double M0 {
            get {
                return this.M0Field;
            }
            set {
                if ((this.M0Field.Equals(value) != true)) {
                    this.M0Field = value;
                    this.RaisePropertyChanged("M0");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double M1 {
            get {
                return this.M1Field;
            }
            set {
                if ((this.M1Field.Equals(value) != true)) {
                    this.M1Field = value;
                    this.RaisePropertyChanged("M1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCSBConstraint", Namespace="http://schemas.datacontract.org/2004/07/treeDiM.StackBuilder.WCFAppServ")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintInt))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintDouble))]
    public partial class DCSBConstraint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCCompFormat", Namespace="http://schemas.datacontract.org/2004/07/treeDiM.StackBuilder.WCFAppServ")]
    [System.SerializableAttribute()]
    public partial class DCCompFormat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private treeDiM.StackBuilder.WCFService.Test.SB_SR.OutFormat FormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompSize SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.OutFormat Format {
            get {
                return this.FormatField;
            }
            set {
                if ((this.FormatField.Equals(value) != true)) {
                    this.FormatField = value;
                    this.RaisePropertyChanged("Format");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompSize Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCCompSize", Namespace="http://schemas.datacontract.org/2004/07/treeDiM.StackBuilder.WCFAppServ")]
    [System.SerializableAttribute()]
    public partial class DCCompSize : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CYField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CX {
            get {
                return this.CXField;
            }
            set {
                if ((this.CXField.Equals(value) != true)) {
                    this.CXField = value;
                    this.RaisePropertyChanged("CX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CY {
            get {
                return this.CYField;
            }
            set {
                if ((this.CYField.Equals(value) != true)) {
                    this.CYField = value;
                    this.RaisePropertyChanged("CY");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutFormat", Namespace="http://schemas.datacontract.org/2004/07/treeDiM.StackBuilder.WCFAppServ")]
    public enum OutFormat : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NONE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IMAGE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CFF2 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DXF = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AI = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PDF = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DES = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCSBSolution", Namespace="http://schemas.datacontract.org/2004/07/treeDiM.StackBuilder.WCFAppServ")]
    [System.SerializableAttribute()]
    public partial class DCSBSolution : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBDim3D BBoxLoadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBDim3D BBoxTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CaseCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EfficiencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InterlayerCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LayerCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> NetWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFileOutput OutFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PalletMapPhraseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WeightLoadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WeightTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBDim3D BBoxLoad {
            get {
                return this.BBoxLoadField;
            }
            set {
                if ((object.ReferenceEquals(this.BBoxLoadField, value) != true)) {
                    this.BBoxLoadField = value;
                    this.RaisePropertyChanged("BBoxLoad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBDim3D BBoxTotal {
            get {
                return this.BBoxTotalField;
            }
            set {
                if ((object.ReferenceEquals(this.BBoxTotalField, value) != true)) {
                    this.BBoxTotalField = value;
                    this.RaisePropertyChanged("BBoxTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CaseCount {
            get {
                return this.CaseCountField;
            }
            set {
                if ((this.CaseCountField.Equals(value) != true)) {
                    this.CaseCountField = value;
                    this.RaisePropertyChanged("CaseCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Efficiency {
            get {
                return this.EfficiencyField;
            }
            set {
                if ((this.EfficiencyField.Equals(value) != true)) {
                    this.EfficiencyField = value;
                    this.RaisePropertyChanged("Efficiency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InterlayerCount {
            get {
                return this.InterlayerCountField;
            }
            set {
                if ((this.InterlayerCountField.Equals(value) != true)) {
                    this.InterlayerCountField = value;
                    this.RaisePropertyChanged("InterlayerCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LayerCount {
            get {
                return this.LayerCountField;
            }
            set {
                if ((this.LayerCountField.Equals(value) != true)) {
                    this.LayerCountField = value;
                    this.RaisePropertyChanged("LayerCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> NetWeight {
            get {
                return this.NetWeightField;
            }
            set {
                if ((this.NetWeightField.Equals(value) != true)) {
                    this.NetWeightField = value;
                    this.RaisePropertyChanged("NetWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFileOutput OutFile {
            get {
                return this.OutFileField;
            }
            set {
                if ((object.ReferenceEquals(this.OutFileField, value) != true)) {
                    this.OutFileField = value;
                    this.RaisePropertyChanged("OutFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PalletMapPhrase {
            get {
                return this.PalletMapPhraseField;
            }
            set {
                if ((object.ReferenceEquals(this.PalletMapPhraseField, value) != true)) {
                    this.PalletMapPhraseField = value;
                    this.RaisePropertyChanged("PalletMapPhrase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double WeightLoad {
            get {
                return this.WeightLoadField;
            }
            set {
                if ((this.WeightLoadField.Equals(value) != true)) {
                    this.WeightLoadField = value;
                    this.RaisePropertyChanged("WeightLoad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double WeightTotal {
            get {
                return this.WeightTotalField;
            }
            set {
                if ((this.WeightTotalField.Equals(value) != true)) {
                    this.WeightTotalField = value;
                    this.RaisePropertyChanged("WeightTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCCompFileOutput", Namespace="http://schemas.datacontract.org/2004/07/treeDiM.StackBuilder.WCFAppServ")]
    [System.SerializableAttribute()]
    public partial class DCCompFileOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BytesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFormat FormatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFormat Format {
            get {
                return this.FormatField;
            }
            set {
                if ((object.ReferenceEquals(this.FormatField, value) != true)) {
                    this.FormatField = value;
                    this.RaisePropertyChanged("Format");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SB_SR.IStackBuilder")]
    public interface IStackBuilder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStackBuilder/SB_GetCasePalletBestSolution", ReplyAction="http://tempuri.org/IStackBuilder/SB_GetCasePalletBestSolutionResponse")]
        treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBSolution SB_GetCasePalletBestSolution(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBCase sbCase, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBPallet sbPallet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBInterlayer sbInterlayer, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintSet sbConstraintSet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFormat expectedFormat, bool showCotations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStackBuilder/SB_GetCasePalletBestSolution", ReplyAction="http://tempuri.org/IStackBuilder/SB_GetCasePalletBestSolutionResponse")]
        System.Threading.Tasks.Task<treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBSolution> SB_GetCasePalletBestSolutionAsync(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBCase sbCase, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBPallet sbPallet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBInterlayer sbInterlayer, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintSet sbConstraintSet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFormat expectedFormat, bool showCotations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStackBuilder/SB_GetBundlePalletBestSolution", ReplyAction="http://tempuri.org/IStackBuilder/SB_GetBundlePalletBestSolutionResponse")]
        treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBSolution SB_GetBundlePalletBestSolution(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBBundle sbBundle, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBPallet sbPallet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBInterlayer sbInterlayer, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintSet sbConstraintSet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFormat expectedFormat, bool showCotations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStackBuilder/SB_GetBundlePalletBestSolution", ReplyAction="http://tempuri.org/IStackBuilder/SB_GetBundlePalletBestSolutionResponse")]
        System.Threading.Tasks.Task<treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBSolution> SB_GetBundlePalletBestSolutionAsync(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBBundle sbBundle, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBPallet sbPallet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBInterlayer sbInterlayer, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintSet sbConstraintSet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFormat expectedFormat, bool showCotations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStackBuilder/SB_GetBundleCaseBestSolution", ReplyAction="http://tempuri.org/IStackBuilder/SB_GetBundleCaseBestSolutionResponse")]
        treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBSolution SB_GetBundleCaseBestSolution(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBBundle sbBundle, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBCase sbCase, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintSet sbConstraintSet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFormat expectedFormat, bool showCotations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStackBuilder/SB_GetBundleCaseBestSolution", ReplyAction="http://tempuri.org/IStackBuilder/SB_GetBundleCaseBestSolutionResponse")]
        System.Threading.Tasks.Task<treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBSolution> SB_GetBundleCaseBestSolutionAsync(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBBundle sbBundle, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBCase sbCase, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintSet sbConstraintSet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFormat expectedFormat, bool showCotations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStackBuilder/SB_GetBoxCaseBestSolution", ReplyAction="http://tempuri.org/IStackBuilder/SB_GetBoxCaseBestSolutionResponse")]
        treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBSolution SB_GetBoxCaseBestSolution(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBCase sbBox, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBCase sbCase, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBInterlayer sbInterlayer, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintSet cSBConstraintSet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFormat expectedFormat, bool showCotations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStackBuilder/SB_GetBoxCaseBestSolution", ReplyAction="http://tempuri.org/IStackBuilder/SB_GetBoxCaseBestSolutionResponse")]
        System.Threading.Tasks.Task<treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBSolution> SB_GetBoxCaseBestSolutionAsync(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBCase sbBox, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBCase sbCase, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBInterlayer sbInterlayer, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintSet cSBConstraintSet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFormat expectedFormat, bool showCotations);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStackBuilderChannel : treeDiM.StackBuilder.WCFService.Test.SB_SR.IStackBuilder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StackBuilderClient : System.ServiceModel.ClientBase<treeDiM.StackBuilder.WCFService.Test.SB_SR.IStackBuilder>, treeDiM.StackBuilder.WCFService.Test.SB_SR.IStackBuilder {
        
        public StackBuilderClient() {
        }
        
        public StackBuilderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StackBuilderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StackBuilderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StackBuilderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBSolution SB_GetCasePalletBestSolution(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBCase sbCase, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBPallet sbPallet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBInterlayer sbInterlayer, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintSet sbConstraintSet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFormat expectedFormat, bool showCotations) {
            return base.Channel.SB_GetCasePalletBestSolution(sbCase, sbPallet, sbInterlayer, sbConstraintSet, expectedFormat, showCotations);
        }
        
        public System.Threading.Tasks.Task<treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBSolution> SB_GetCasePalletBestSolutionAsync(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBCase sbCase, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBPallet sbPallet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBInterlayer sbInterlayer, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintSet sbConstraintSet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFormat expectedFormat, bool showCotations) {
            return base.Channel.SB_GetCasePalletBestSolutionAsync(sbCase, sbPallet, sbInterlayer, sbConstraintSet, expectedFormat, showCotations);
        }
        
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBSolution SB_GetBundlePalletBestSolution(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBBundle sbBundle, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBPallet sbPallet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBInterlayer sbInterlayer, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintSet sbConstraintSet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFormat expectedFormat, bool showCotations) {
            return base.Channel.SB_GetBundlePalletBestSolution(sbBundle, sbPallet, sbInterlayer, sbConstraintSet, expectedFormat, showCotations);
        }
        
        public System.Threading.Tasks.Task<treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBSolution> SB_GetBundlePalletBestSolutionAsync(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBBundle sbBundle, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBPallet sbPallet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBInterlayer sbInterlayer, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintSet sbConstraintSet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFormat expectedFormat, bool showCotations) {
            return base.Channel.SB_GetBundlePalletBestSolutionAsync(sbBundle, sbPallet, sbInterlayer, sbConstraintSet, expectedFormat, showCotations);
        }
        
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBSolution SB_GetBundleCaseBestSolution(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBBundle sbBundle, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBCase sbCase, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintSet sbConstraintSet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFormat expectedFormat, bool showCotations) {
            return base.Channel.SB_GetBundleCaseBestSolution(sbBundle, sbCase, sbConstraintSet, expectedFormat, showCotations);
        }
        
        public System.Threading.Tasks.Task<treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBSolution> SB_GetBundleCaseBestSolutionAsync(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBBundle sbBundle, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBCase sbCase, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintSet sbConstraintSet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFormat expectedFormat, bool showCotations) {
            return base.Channel.SB_GetBundleCaseBestSolutionAsync(sbBundle, sbCase, sbConstraintSet, expectedFormat, showCotations);
        }
        
        public treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBSolution SB_GetBoxCaseBestSolution(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBCase sbBox, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBCase sbCase, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBInterlayer sbInterlayer, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintSet cSBConstraintSet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFormat expectedFormat, bool showCotations) {
            return base.Channel.SB_GetBoxCaseBestSolution(sbBox, sbCase, sbInterlayer, cSBConstraintSet, expectedFormat, showCotations);
        }
        
        public System.Threading.Tasks.Task<treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBSolution> SB_GetBoxCaseBestSolutionAsync(treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBCase sbBox, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBCase sbCase, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBInterlayer sbInterlayer, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCSBConstraintSet cSBConstraintSet, treeDiM.StackBuilder.WCFService.Test.SB_SR.DCCompFormat expectedFormat, bool showCotations) {
            return base.Channel.SB_GetBoxCaseBestSolutionAsync(sbBox, sbCase, sbInterlayer, cSBConstraintSet, expectedFormat, showCotations);
        }
    }
}
