//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace treeDiM.StackBuilder.Reporting.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("treeDiM.StackBuilder.Reporting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HyperText Markup Language (*html)|*.html|All files (*.*)|*.*.
        /// </summary>
        internal static string ID_FILTER_HTML {
            get {
                return ResourceManager.GetString("ID_FILTER_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Microsoft Office Word (*.doc;*.docx)|*.doc;*.docx|All Files (*.*)|*.*.
        /// </summary>
        internal static string ID_FILTER_MSWORD {
            get {
                return ResourceManager.GetString("ID_FILTER_MSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abobe Acrobat (*.pdf)|*.pdf.
        /// </summary>
        internal static string ID_FILTER_PDF {
            get {
                return ResourceManager.GetString("ID_FILTER_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Report.
        /// </summary>
        internal static string ID_REPORT {
            get {
                return ResourceManager.GetString("ID_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Report {0}.
        /// </summary>
        internal static string ID_REPORTANALYSIS {
            get {
                return ResourceManager.GetString("ID_REPORTANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analysis ({0}).
        /// </summary>
        internal static string ID_RN_ANALYSIS {
            get {
                return ResourceManager.GetString("ID_RN_ANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrangement.
        /// </summary>
        internal static string ID_RN_ARRANGEMENT {
            get {
                return ResourceManager.GetString("ID_RN_ARRANGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authors.
        /// </summary>
        internal static string ID_RN_AUTHORS {
            get {
                return ResourceManager.GetString("ID_RN_AUTHORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Box.
        /// </summary>
        internal static string ID_RN_BOX {
            get {
                return ResourceManager.GetString("ID_RN_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bundle.
        /// </summary>
        internal static string ID_RN_BUNDLE {
            get {
                return ResourceManager.GetString("ID_RN_BUNDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Case.
        /// </summary>
        internal static string ID_RN_CASE {
            get {
                return ResourceManager.GetString("ID_RN_CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Company logo.
        /// </summary>
        internal static string ID_RN_COMPANYLOGO {
            get {
                return ResourceManager.GetString("ID_RN_COMPANYLOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Constraint set.
        /// </summary>
        internal static string ID_RN_CONSTRAINTSET {
            get {
                return ResourceManager.GetString("ID_RN_CONSTRAINTSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cylinder.
        /// </summary>
        internal static string ID_RN_CYLINDER {
            get {
                return ResourceManager.GetString("ID_RN_CYLINDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        internal static string ID_RN_DATE {
            get {
                return ResourceManager.GetString("ID_RN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default.
        /// </summary>
        internal static string ID_RN_DEFAULT {
            get {
                return ResourceManager.GetString("ID_RN_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        internal static string ID_RN_DESCRIPTION {
            get {
                return ResourceManager.GetString("ID_RN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dimensions.
        /// </summary>
        internal static string ID_RN_DIMENSIONS {
            get {
                return ResourceManager.GetString("ID_RN_DIMENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inner dimensions.
        /// </summary>
        internal static string ID_RN_DIMENSIONSINNER {
            get {
                return ResourceManager.GetString("ID_RN_DIMENSIONSINNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Outer dimensions.
        /// </summary>
        internal static string ID_RN_DIMENSIONSOUTER {
            get {
                return ResourceManager.GetString("ID_RN_DIMENSIONSOUTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image.
        /// </summary>
        internal static string ID_RN_IMAGE {
            get {
                return ResourceManager.GetString("ID_RN_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interlayer.
        /// </summary>
        internal static string ID_RN_INTERLAYER {
            get {
                return ResourceManager.GetString("ID_RN_INTERLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Layers.
        /// </summary>
        internal static string ID_RN_LAYERS {
            get {
                return ResourceManager.GetString("ID_RN_LAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum height.
        /// </summary>
        internal static string ID_RN_MAXIMUMHEIGHT {
            get {
                return ResourceManager.GetString("ID_RN_MAXIMUMHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum number.
        /// </summary>
        internal static string ID_RN_MAXIMUMNUMBER {
            get {
                return ResourceManager.GetString("ID_RN_MAXIMUMNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum weight.
        /// </summary>
        internal static string ID_RN_MAXIMUMWEIGHT {
            get {
                return ResourceManager.GetString("ID_RN_MAXIMUMWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Overhang.
        /// </summary>
        internal static string ID_RN_OVERHANG {
            get {
                return ResourceManager.GetString("ID_RN_OVERHANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pack.
        /// </summary>
        internal static string ID_RN_PACK {
            get {
                return ResourceManager.GetString("ID_RN_PACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pallet.
        /// </summary>
        internal static string ID_RN_PALLET {
            get {
                return ResourceManager.GetString("ID_RN_PALLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Solution.
        /// </summary>
        internal static string ID_RN_SOLUTION {
            get {
                return ResourceManager.GetString("ID_RN_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spaces.
        /// </summary>
        internal static string ID_RN_SPACES {
            get {
                return ResourceManager.GetString("ID_RN_SPACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Truck.
        /// </summary>
        internal static string ID_RN_TRUCK {
            get {
                return ResourceManager.GetString("ID_RN_TRUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Iso.
        /// </summary>
        internal static string ID_RN_VIEWISO {
            get {
                return ResourceManager.GetString("ID_RN_VIEWISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Front/Left/Right/Back.
        /// </summary>
        internal static string ID_RN_VIEWS {
            get {
                return ResourceManager.GetString("ID_RN_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Volume efficiency.
        /// </summary>
        internal static string ID_RN_VOLUMEEFFICIENCY {
            get {
                return ResourceManager.GetString("ID_RN_VOLUMEEFFICIENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weight.
        /// </summary>
        internal static string ID_RN_WEIGHT {
            get {
                return ResourceManager.GetString("ID_RN_WEIGHT", resourceCulture);
            }
        }
    }
}
