//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace treeDiM.StackBuilder.Reporting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("treeDiM.StackBuilder.Reporting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case_{0}x{1}x{2}.
        /// </summary>
        internal static string ID_CASE_DIMENSIONS {
            get {
                return ResourceManager.GetString("ID_CASE_DIMENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HyperText Markup Language (*html)|*.html|All files (*.*)|*.*.
        /// </summary>
        internal static string ID_FILTER_HTML {
            get {
                return ResourceManager.GetString("ID_FILTER_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Office Word (*.doc;*.docx)|*.doc;*.docx|All Files (*.*)|*.*.
        /// </summary>
        internal static string ID_FILTER_MSWORD {
            get {
                return ResourceManager.GetString("ID_FILTER_MSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abobe Acrobat (*.pdf)|*.pdf.
        /// </summary>
        internal static string ID_FILTER_PDF {
            get {
                return ResourceManager.GetString("ID_FILTER_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string ID_REPORT {
            get {
                return ResourceManager.GetString("ID_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report {0}.
        /// </summary>
        internal static string ID_REPORT_CAPTION {
            get {
                return ResourceManager.GetString("ID_REPORT_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis ({0}).
        /// </summary>
        internal static string ID_RN_ANALYSIS {
            get {
                return ResourceManager.GetString("ID_RN_ANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangement.
        /// </summary>
        internal static string ID_RN_ARRANGEMENT {
            get {
                return ResourceManager.GetString("ID_RN_ARRANGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string ID_RN_AUTHORS {
            get {
                return ResourceManager.GetString("ID_RN_AUTHORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottle.
        /// </summary>
        internal static string ID_RN_BOTTLE {
            get {
                return ResourceManager.GetString("ID_RN_BOTTLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        internal static string ID_RN_BOX {
            get {
                return ResourceManager.GetString("ID_RN_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle.
        /// </summary>
        internal static string ID_RN_BUNDLE {
            get {
                return ResourceManager.GetString("ID_RN_BUNDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case.
        /// </summary>
        internal static string ID_RN_CASE {
            get {
                return ResourceManager.GetString("ID_RN_CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company logo.
        /// </summary>
        internal static string ID_RN_COMPANYLOGO {
            get {
                return ResourceManager.GetString("ID_RN_COMPANYLOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint set.
        /// </summary>
        internal static string ID_RN_CONSTRAINTSET {
            get {
                return ResourceManager.GetString("ID_RN_CONSTRAINTSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder.
        /// </summary>
        internal static string ID_RN_CYLINDER {
            get {
                return ResourceManager.GetString("ID_RN_CYLINDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ID_RN_DATE {
            get {
                return ResourceManager.GetString("ID_RN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string ID_RN_DEFAULT {
            get {
                return ResourceManager.GetString("ID_RN_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ID_RN_DESCRIPTION {
            get {
                return ResourceManager.GetString("ID_RN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        internal static string ID_RN_DIMENSIONS {
            get {
                return ResourceManager.GetString("ID_RN_DIMENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner dimensions.
        /// </summary>
        internal static string ID_RN_DIMENSIONSINNER {
            get {
                return ResourceManager.GetString("ID_RN_DIMENSIONSINNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer dimensions.
        /// </summary>
        internal static string ID_RN_DIMENSIONSOUTER {
            get {
                return ResourceManager.GetString("ID_RN_DIMENSIONSOUTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic BCT.
        /// </summary>
        internal static string ID_RN_DYNAMICBCT {
            get {
                return ResourceManager.GetString("ID_RN_DYNAMICBCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string ID_RN_IMAGE {
            get {
                return ResourceManager.GetString("ID_RN_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string ID_RN_IMAGES {
            get {
                return ResourceManager.GetString("ID_RN_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlayer.
        /// </summary>
        internal static string ID_RN_INTERLAYER {
            get {
                return ResourceManager.GetString("ID_RN_INTERLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string ID_RN_ITEMNUMBERS {
            get {
                return ResourceManager.GetString("ID_RN_ITEMNUMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        internal static string ID_RN_LAYERS {
            get {
                return ResourceManager.GetString("ID_RN_LAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load dimensions.
        /// </summary>
        internal static string ID_RN_LOADDIMENSIONS {
            get {
                return ResourceManager.GetString("ID_RN_LOADDIMENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load weight.
        /// </summary>
        internal static string ID_RN_LOADWEIGHT {
            get {
                return ResourceManager.GetString("ID_RN_LOADWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string ID_RN_MATERIAL {
            get {
                return ResourceManager.GetString("ID_RN_MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum height.
        /// </summary>
        internal static string ID_RN_MAXIMUMHEIGHT {
            get {
                return ResourceManager.GetString("ID_RN_MAXIMUMHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number.
        /// </summary>
        internal static string ID_RN_MAXIMUMNUMBER {
            get {
                return ResourceManager.GetString("ID_RN_MAXIMUMNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum weight.
        /// </summary>
        internal static string ID_RN_MAXIMUMWEIGHT {
            get {
                return ResourceManager.GetString("ID_RN_MAXIMUMWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ID_RN_NAME {
            get {
                return ResourceManager.GetString("ID_RN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of interlayers.
        /// </summary>
        internal static string ID_RN_NOINTERLAYERS {
            get {
                return ResourceManager.GetString("ID_RN_NOINTERLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers x Cases.
        /// </summary>
        internal static string ID_RN_NOLAYERSBYNOCASES {
            get {
                return ResourceManager.GetString("ID_RN_NOLAYERSBYNOCASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall dimensions.
        /// </summary>
        internal static string ID_RN_OVERALLDIMENSIONS {
            get {
                return ResourceManager.GetString("ID_RN_OVERALLDIMENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overhang.
        /// </summary>
        internal static string ID_RN_OVERHANG {
            get {
                return ResourceManager.GetString("ID_RN_OVERHANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack.
        /// </summary>
        internal static string ID_RN_PACK {
            get {
                return ResourceManager.GetString("ID_RN_PACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackStress.
        /// </summary>
        internal static string ID_RN_PACKSTRESS {
            get {
                return ResourceManager.GetString("ID_RN_PACKSTRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet.
        /// </summary>
        internal static string ID_RN_PALLET {
            get {
                return ResourceManager.GetString("ID_RN_PALLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palletisation.
        /// </summary>
        internal static string ID_RN_PALLETISATION {
            get {
                return ResourceManager.GetString("ID_RN_PALLETISATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        internal static string ID_RN_SOLUTION {
            get {
                return ResourceManager.GetString("ID_RN_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces.
        /// </summary>
        internal static string ID_RN_SPACES {
            get {
                return ResourceManager.GetString("ID_RN_SPACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static BCT.
        /// </summary>
        internal static string ID_RN_STATICBCT {
            get {
                return ResourceManager.GetString("ID_RN_STATICBCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total weight.
        /// </summary>
        internal static string ID_RN_TOTALWEIGHT {
            get {
                return ResourceManager.GetString("ID_RN_TOTALWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck.
        /// </summary>
        internal static string ID_RN_TRUCK {
            get {
                return ResourceManager.GetString("ID_RN_TRUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iso.
        /// </summary>
        internal static string ID_RN_VIEWISO {
            get {
                return ResourceManager.GetString("ID_RN_VIEWISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front/Left/Right/Back.
        /// </summary>
        internal static string ID_RN_VIEWS {
            get {
                return ResourceManager.GetString("ID_RN_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume efficiency.
        /// </summary>
        internal static string ID_RN_VOLUMEEFFICIENCY {
            get {
                return ResourceManager.GetString("ID_RN_VOLUMEEFFICIENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string ID_RN_WEIGHT {
            get {
                return ResourceManager.GetString("ID_RN_WEIGHT", resourceCulture);
            }
        }
    }
}
