//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace treeDiM.StackBuilder.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("treeDiM.StackBuilder.Desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Analysis {
            get {
                object obj = ResourceManager.GetObject("Analysis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalysisBundle {
            get {
                object obj = ResourceManager.GetObject("AnalysisBundle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalysisCylinder {
            get {
                object obj = ResourceManager.GetObject("AnalysisCylinder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalysisHCylinder {
            get {
                object obj = ResourceManager.GetObject("AnalysisHCylinder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalysisStackingStrength {
            get {
                object obj = ResourceManager.GetObject("AnalysisStackingStrength", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Box {
            get {
                object obj = ResourceManager.GetObject("Box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BoxCaseAnalysis {
            get {
                object obj = ResourceManager.GetObject("BoxCaseAnalysis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bundle {
            get {
                object obj = ResourceManager.GetObject("Bundle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Case {
            get {
                object obj = ResourceManager.GetObject("Case", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CaseAnalysis {
            get {
                object obj = ResourceManager.GetObject("CaseAnalysis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cylinder {
            get {
                object obj = ResourceManager.GetObject("Cylinder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Database {
            get {
                object obj = ResourceManager.GetObject("Database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FileNew {
            get {
                object obj = ResourceManager.GetObject("FileNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FileOpen {
            get {
                object obj = ResourceManager.GetObject("FileOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FileSave {
            get {
                object obj = ResourceManager.GetObject("FileSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FileSaveAll {
            get {
                object obj = ResourceManager.GetObject("FileSaveAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A1.
        /// </summary>
        internal static string ID_A1 {
            get {
                return ResourceManager.GetString("ID_A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A2.
        /// </summary>
        internal static string ID_A2 {
            get {
                return ResourceManager.GetString("ID_A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A3.
        /// </summary>
        internal static string ID_A3 {
            get {
                return ResourceManager.GetString("ID_A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About {0}.
        /// </summary>
        internal static string ID_ABOUT {
            get {
                return ResourceManager.GetString("ID_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new analysis....
        /// </summary>
        internal static string ID_ADDNEWANALYSIS {
            get {
                return ResourceManager.GetString("ID_ADDNEWANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new box....
        /// </summary>
        internal static string ID_ADDNEWBOX {
            get {
                return ResourceManager.GetString("ID_ADDNEWBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new box/case analysis....
        /// </summary>
        internal static string ID_ADDNEWBOXCASEANALYSIS {
            get {
                return ResourceManager.GetString("ID_ADDNEWBOXCASEANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new bundle....
        /// </summary>
        internal static string ID_ADDNEWBUNDLE {
            get {
                return ResourceManager.GetString("ID_ADDNEWBUNDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new bundle analysis....
        /// </summary>
        internal static string ID_ADDNEWBUNDLEANALYSIS {
            get {
                return ResourceManager.GetString("ID_ADDNEWBUNDLEANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new case....
        /// </summary>
        internal static string ID_ADDNEWCASE {
            get {
                return ResourceManager.GetString("ID_ADDNEWCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new case analysis....
        /// </summary>
        internal static string ID_ADDNEWCASEANALYSIS {
            get {
                return ResourceManager.GetString("ID_ADDNEWCASEANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new cylinder....
        /// </summary>
        internal static string ID_ADDNEWCYLINDER {
            get {
                return ResourceManager.GetString("ID_ADDNEWCYLINDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new cylinder analysis....
        /// </summary>
        internal static string ID_ADDNEWCYLINDERANALYSIS {
            get {
                return ResourceManager.GetString("ID_ADDNEWCYLINDERANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new ECT analysis....
        /// </summary>
        internal static string ID_ADDNEWECTANALYSIS {
            get {
                return ResourceManager.GetString("ID_ADDNEWECTANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new interlayer....
        /// </summary>
        internal static string ID_ADDNEWINTERLAYER {
            get {
                return ResourceManager.GetString("ID_ADDNEWINTERLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new Pack/Pallet analysis....
        /// </summary>
        internal static string ID_ADDNEWPACKANALYSIS {
            get {
                return ResourceManager.GetString("ID_ADDNEWPACKANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new pallet....
        /// </summary>
        internal static string ID_ADDNEWPALLET {
            get {
                return ResourceManager.GetString("ID_ADDNEWPALLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new pallet cap....
        /// </summary>
        internal static string ID_ADDNEWPALLETCAP {
            get {
                return ResourceManager.GetString("ID_ADDNEWPALLETCAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new pallet corners....
        /// </summary>
        internal static string ID_ADDNEWPALLETCORNERS {
            get {
                return ResourceManager.GetString("ID_ADDNEWPALLETCORNERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new pallet film....
        /// </summary>
        internal static string ID_ADDNEWPALLETFILM {
            get {
                return ResourceManager.GetString("ID_ADDNEWPALLETFILM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new truck....
        /// </summary>
        internal static string ID_ADDNEWTRUCK {
            get {
                return ResourceManager.GetString("ID_ADDNEWTRUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new truck analysis....
        /// </summary>
        internal static string ID_ADDNEWTRUCKANALYSIS {
            get {
                return ResourceManager.GetString("ID_ADDNEWTRUCKANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow aligned and/or alternate layers.
        /// </summary>
        internal static string ID_ALLOWALIGNEDORALTERNATELAYERS {
            get {
                return ResourceManager.GetString("ID_ALLOWALIGNEDORALTERNATELAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analysis.
        /// </summary>
        internal static string ID_ANALYSIS {
            get {
                return ResourceManager.GetString("ID_ANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analysis has no solutions?\nTo many contraints?.
        /// </summary>
        internal static string ID_ANALYSISHASNOSOLUTION {
            get {
                return ResourceManager.GetString("ID_ANALYSISHASNOSOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analysis {0} has no valid solution..
        /// </summary>
        internal static string ID_ANALYSISHASNOVALIDSOLUTION {
            get {
                return ResourceManager.GetString("ID_ANALYSISHASNOVALIDSOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Area.
        /// </summary>
        internal static string ID_AREA {
            get {
                return ResourceManager.GetString("ID_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import auto.
        /// </summary>
        internal static string ID_AUTOIMPORT {
            get {
                return ResourceManager.GetString("ID_AUTOIMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Box.
        /// </summary>
        internal static string ID_BOX {
            get {
                return ResourceManager.GetString("ID_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Box/Case count.
        /// </summary>
        internal static string ID_BOXCASECOUNT {
            get {
                return ResourceManager.GetString("ID_BOXCASECOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Box/Case.
        /// </summary>
        internal static string ID_BOXCOUNT {
            get {
                return ResourceManager.GetString("ID_BOXCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Box {0} does not fit in case {1}..
        /// </summary>
        internal static string ID_BOXDOESNOTFITINCASE {
            get {
                return ResourceManager.GetString("ID_BOXDOESNOTFITINCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Boxes.
        /// </summary>
        internal static string ID_BOXES {
            get {
                return ResourceManager.GetString("ID_BOXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bundle.
        /// </summary>
        internal static string ID_BUNDLE {
            get {
                return ResourceManager.GetString("ID_BUNDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weight limit can not be used because {0} as no mass..
        /// </summary>
        internal static string ID_CANNOTUSEWEIGHTLIMIT {
            get {
                return ResourceManager.GetString("ID_CANNOTUSEWEIGHTLIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Case.
        /// </summary>
        internal static string ID_CASE {
            get {
                return ResourceManager.GetString("ID_CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot create case analysis as the constraint set appears to be invalid..
        /// </summary>
        internal static string ID_CASEANALYSIS_INVALIDCONSTRAINTSET {
            get {
                return ResourceManager.GetString("ID_CASEANALYSIS_INVALIDCONSTRAINTSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à # Cases.
        /// </summary>
        internal static string ID_CASECOUNT {
            get {
                return ResourceManager.GetString("ID_CASECOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}
        ///{1}x{2}.
        /// </summary>
        internal static string ID_CASECOUNTFORMATSTRING {
            get {
                return ResourceManager.GetString("ID_CASECOUNTFORMATSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Case dimensions.
        /// </summary>
        internal static string ID_CASEDIMENSIONS {
            get {
                return ResourceManager.GetString("ID_CASEDIMENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Case inside dimensions.
        /// </summary>
        internal static string ID_CASEINSIDEDIMENSIONS {
            get {
                return ResourceManager.GetString("ID_CASEINSIDEDIMENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Limit reached.
        /// </summary>
        internal static string ID_CASELIMIT {
            get {
                return ResourceManager.GetString("ID_CASELIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Caisse.
        /// </summary>
        internal static string ID_CASENAME {
            get {
                return ResourceManager.GetString("ID_CASENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Case of boxes.
        /// </summary>
        internal static string ID_CASEOFBOXES {
            get {
                return ResourceManager.GetString("ID_CASEOFBOXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à # Cases/Layer.
        /// </summary>
        internal static string ID_CASEPERLAYERCOUNT {
            get {
                return ResourceManager.GetString("ID_CASEPERLAYERCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Case/pallet.
        /// </summary>
        internal static string ID_CASEPERPALLET {
            get {
                return ResourceManager.GetString("ID_CASEPERPALLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cases.
        /// </summary>
        internal static string ID_CASES {
            get {
                return ResourceManager.GetString("ID_CASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cases/Layer.
        /// </summary>
        internal static string ID_CASESLAYER {
            get {
                return ResourceManager.GetString("ID_CASESLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cases/Pallet.
        /// </summary>
        internal static string ID_CASESPALLET {
            get {
                return ResourceManager.GetString("ID_CASESPALLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Case weight ({0}).
        /// </summary>
        internal static string ID_CASEWEIGHT {
            get {
                return ResourceManager.GetString("ID_CASEWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Google Chrome browser needs to be installed to visualize collada/webGL animations..
        /// </summary>
        internal static string ID_CHROMEISNOTINSTALLED {
            get {
                return ResourceManager.GetString("ID_CHROMEISNOTINSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string ID_CLOSE {
            get {
                return ResourceManager.GetString("ID_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à # CSU.
        /// </summary>
        internal static string ID_CONSUMERSALESUNITS {
            get {
                return ResourceManager.GetString("ID_CONSUMERSALESUNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cylinder.
        /// </summary>
        internal static string ID_CYLINDER {
            get {
                return ResourceManager.GetString("ID_CYLINDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cylinder count.
        /// </summary>
        internal static string ID_CYLINDERCOUNT {
            get {
                return ResourceManager.GetString("ID_CYLINDERCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cylinders.
        /// </summary>
        internal static string ID_CYLINDERS {
            get {
                return ResourceManager.GetString("ID_CYLINDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pallet solution database is empty.
        ///Closing form....
        /// </summary>
        internal static string ID_DATABASEEMPTY {
            get {
                return ResourceManager.GetString("ID_DATABASEEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Define at least one stacking pattern.
        /// </summary>
        internal static string ID_DEFINEATLEASTONEPATTERN {
            get {
                return ResourceManager.GetString("ID_DEFINEATLEASTONEPATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Define at least one vertical axis.
        /// </summary>
        internal static string ID_DEFINEATLEASTONEVERTICALAXIS {
            get {
                return ResourceManager.GetString("ID_DEFINEATLEASTONEVERTICALAXIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Define a valid file path..
        /// </summary>
        internal static string ID_DEFINEVALIDFILEPATH {
            get {
                return ResourceManager.GetString("ID_DEFINEVALIDFILEPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string ID_DELETE {
            get {
                return ResourceManager.GetString("ID_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete {0}.
        /// </summary>
        internal static string ID_DELETEITEM {
            get {
                return ResourceManager.GetString("ID_DELETEITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has the following dependencies:
        ///{1}
        ///If you proceed with the modifications, analyses will be recomputed and any selected solutions removed.
        ///Continue?.
        /// </summary>
        internal static string ID_DEPENDINGANALYSES {
            get {
                return ResourceManager.GetString("ID_DEPENDINGANALYSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        internal static string ID_DESCRIPTION {
            get {
                return ResourceManager.GetString("ID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deselect.
        /// </summary>
        internal static string ID_DESELECT {
            get {
                return ResourceManager.GetString("ID_DESELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inner diameter ({0}).
        /// </summary>
        internal static string ID_DIAMETERINNER_WU {
            get {
                return ResourceManager.GetString("ID_DIAMETERINNER_WU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Outer diameter ({0}).
        /// </summary>
        internal static string ID_DIAMETEROUTER_WU {
            get {
                return ResourceManager.GetString("ID_DIAMETEROUTER_WU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dimensions ({0}).
        /// </summary>
        internal static string ID_DIMENSIONS {
            get {
                return ResourceManager.GetString("ID_DIMENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dim. ext. ({0}).
        /// </summary>
        internal static string ID_DIMEXT_WU {
            get {
                return ResourceManager.GetString("ID_DIMEXT_WU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dim. int. ({0}).
        /// </summary>
        internal static string ID_DIMINT_WU {
            get {
                return ResourceManager.GetString("ID_DIMINT_WU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Debugging.
        /// </summary>
        internal static string ID_DISPLAYDEBUGGING {
            get {
                return ResourceManager.GetString("ID_DISPLAYDEBUGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dimensions Case/Pallet.
        /// </summary>
        internal static string ID_DISPLAYDIMENSIONSCASEPALLET {
            get {
                return ResourceManager.GetString("ID_DISPLAYDIMENSIONSCASEPALLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language &amp; Measurement system.
        /// </summary>
        internal static string ID_DISPLAYMEASUREMENTSYSTEM {
            get {
                return ResourceManager.GetString("ID_DISPLAYMEASUREMENTSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pallet edition parameters.
        /// </summary>
        internal static string ID_DISPLAYPALLETEDITION {
            get {
                return ResourceManager.GetString("ID_DISPLAYPALLETEDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plugins.
        /// </summary>
        internal static string ID_DISPLAYPLUGINS {
            get {
                return ResourceManager.GetString("ID_DISPLAYPLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reporting.
        /// </summary>
        internal static string ID_DISPLAYREPORTING {
            get {
                return ResourceManager.GetString("ID_DISPLAYREPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Done!.
        /// </summary>
        internal static string ID_DONE {
            get {
                return ResourceManager.GetString("ID_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Double-click a layer!.
        /// </summary>
        internal static string ID_DOUBLECLICKALAYER {
            get {
                return ResourceManager.GetString("ID_DOUBLECLICKALAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ECT.
        /// </summary>
        internal static string ID_ECT {
            get {
                return ResourceManager.GetString("ID_ECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edge Crush Test Analysis.
        /// </summary>
        internal static string ID_EDGECRUSHTEST {
            get {
                return ResourceManager.GetString("ID_EDGECRUSHTEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit {0}....
        /// </summary>
        internal static string ID_EDIT {
            get {
                return ResourceManager.GetString("ID_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Efficiency.
        /// </summary>
        internal static string ID_EFFICIENCY {
            get {
                return ResourceManager.GetString("ID_EFFICIENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Efficiency (%).
        /// </summary>
        internal static string ID_EFFICIENCYPERCENTAGE {
            get {
                return ResourceManager.GetString("ID_EFFICIENCYPERCENTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can you confirm that values in Excel sheet ({0}) are expressed using the currently set StackBuilder unit system i.e. {1}?.
        /// </summary>
        internal static string ID_EXCELSHEETUNITSYSTEM {
            get {
                return ResourceManager.GetString("ID_EXCELSHEETUNITSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description field is empty.
        /// </summary>
        internal static string ID_FIELDDESCRIPTIONEMPTY {
            get {
                return ResourceManager.GetString("ID_FIELDDESCRIPTIONEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name field is empty.
        /// </summary>
        internal static string ID_FIELDNAMEEMPTY {
            get {
                return ResourceManager.GetString("ID_FIELDNAMEEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name already exists..
        /// </summary>
        internal static string ID_FIELDNAMEINVALID {
            get {
                return ResourceManager.GetString("ID_FIELDNAMEINVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File {0} could not be found.
        /// </summary>
        internal static string ID_FILENOTFOUND {
            get {
                return ResourceManager.GetString("ID_FILENOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Microsoft Office Word (*.doc;*.docx)|*.doc;*.docx|All Files (*.*)|*.*.
        /// </summary>
        internal static string ID_FILTER_MSWORD {
            get {
                return ResourceManager.GetString("ID_FILTER_MSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate 3D animation file for {0}.
        /// </summary>
        internal static string ID_GENERATECOLLADA {
            get {
                return ResourceManager.GetString("ID_GENERATECOLLADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate a report for {0}.
        /// </summary>
        internal static string ID_GENERATEREPORT {
            get {
                return ResourceManager.GetString("ID_GENERATEREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate HTML report.
        /// </summary>
        internal static string ID_GENERATEREPORTHTML {
            get {
                return ResourceManager.GetString("ID_GENERATEREPORTHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate MS word report.
        /// </summary>
        internal static string ID_GENERATEREPORTMSWORD {
            get {
                return ResourceManager.GetString("ID_GENERATEREPORTMSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate PDF report.
        /// </summary>
        internal static string ID_GENERATEREPORTPDF {
            get {
                return ResourceManager.GetString("ID_GENERATEREPORTPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hatching angle.
        /// </summary>
        internal static string ID_HATCHINGANGLE {
            get {
                return ResourceManager.GetString("ID_HATCHINGANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hatching space.
        /// </summary>
        internal static string ID_HATCHINGSPACING {
            get {
                return ResourceManager.GetString("ID_HATCHINGSPACING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Height.
        /// </summary>
        internal static string ID_HEIGHT {
            get {
                return ResourceManager.GetString("ID_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Height ({0}).
        /// </summary>
        internal static string ID_HEIGHT_WU {
            get {
                return ResourceManager.GetString("ID_HEIGHT_WU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading {0}....
        /// </summary>
        internal static string ID_IMPORTLOADING {
            get {
                return ResourceManager.GetString("ID_IMPORTLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Skipping {0}....
        /// </summary>
        internal static string ID_IMPORTSKIPPING {
            get {
                return ResourceManager.GetString("ID_IMPORTSKIPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Index.
        /// </summary>
        internal static string ID_INDEX {
            get {
                return ResourceManager.GetString("ID_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximal pallet height ({0} {1}) ought to exceed {2} {3}.
        /// </summary>
        internal static string ID_INSUFFICIENTPALLETHEIGHT {
            get {
                return ResourceManager.GetString("ID_INSUFFICIENTPALLETHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum volume is insufficient to pack {0} {1} ..
        /// </summary>
        internal static string ID_INSUFFICIENTVOLUME {
            get {
                return ResourceManager.GetString("ID_INSUFFICIENTVOLUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interlayer.
        /// </summary>
        internal static string ID_INTERLAYER {
            get {
                return ResourceManager.GetString("ID_INTERLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interlayer #.
        /// </summary>
        internal static string ID_INTERLAYERCOUNT {
            get {
                return ResourceManager.GetString("ID_INTERLAYERCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interlayer #.
        /// </summary>
        internal static string ID_INTERLAYERNUMBER {
            get {
                return ResourceManager.GetString("ID_INTERLAYERNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interlayers.
        /// </summary>
        internal static string ID_INTERLAYERS {
            get {
                return ResourceManager.GetString("ID_INTERLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inner diameter ought to be smaller than outer diameter..
        /// </summary>
        internal static string ID_INVALIDDIAMETER {
            get {
                return ResourceManager.GetString("ID_INVALIDDIAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inside height ({0}) ought to be lower than height ({1}).
        /// </summary>
        internal static string ID_INVALIDINSIDEHEIGHT {
            get {
                return ResourceManager.GetString("ID_INVALIDINSIDEHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inside length ({0}) ought to be lower than length ({1}).
        /// </summary>
        internal static string ID_INVALIDINSIDELENGTH {
            get {
                return ResourceManager.GetString("ID_INVALIDINSIDELENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inside width ({0}) ought to be lower than width ({1}).
        /// </summary>
        internal static string ID_INVALIDINSIDEWIDTH {
            get {
                return ResourceManager.GetString("ID_INVALIDINSIDEWIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mass value ought to be positive.
        /// </summary>
        internal static string ID_INVALIDMASS {
            get {
                return ResourceManager.GetString("ID_INVALIDMASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Given name ({0}) is invalid.
        /// </summary>
        internal static string ID_INVALIDNAME {
            get {
                return ResourceManager.GetString("ID_INVALIDNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Net weight ({0}) should not exceed weight ({1}).
        /// </summary>
        internal static string ID_INVALIDNETWEIGHT {
            get {
                return ResourceManager.GetString("ID_INVALIDNETWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Outer dimensions ought to exceed content dimensions....
        /// </summary>
        internal static string ID_INVALIDOUTERDIMENSION {
            get {
                return ResourceManager.GetString("ID_INVALIDOUTERDIMENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thickness should not exceed width.
        /// </summary>
        internal static string ID_INVALIDTHICKNESSWIDTHPAIR {
            get {
                return ResourceManager.GetString("ID_INVALIDTHICKNESSWIDTHPAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Layer.
        /// </summary>
        internal static string ID_LAYER {
            get {
                return ResourceManager.GetString("ID_LAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Layer #.
        /// </summary>
        internal static string ID_LAYERCOUNT {
            get {
                return ResourceManager.GetString("ID_LAYERCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Layer #.
        /// </summary>
        internal static string ID_LAYERNUMBER {
            get {
                return ResourceManager.GetString("ID_LAYERNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Layer pattern.
        /// </summary>
        internal static string ID_LAYERPATTERN {
            get {
                return ResourceManager.GetString("ID_LAYERPATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Layer pattern(s).
        /// </summary>
        internal static string ID_LAYERPATTERNS {
            get {
                return ResourceManager.GetString("ID_LAYERPATTERNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Layers.
        /// </summary>
        internal static string ID_LAYERS {
            get {
                return ResourceManager.GetString("ID_LAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Layer weight ({0}).
        /// </summary>
        internal static string ID_LAYERWEIGHT {
            get {
                return ResourceManager.GetString("ID_LAYERWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Layout.
        /// </summary>
        internal static string ID_LAYOUT {
            get {
                return ResourceManager.GetString("ID_LAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Length.
        /// </summary>
        internal static string ID_LENGTH {
            get {
                return ResourceManager.GetString("ID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Length ({0}).
        /// </summary>
        internal static string ID_LENGTH_WU {
            get {
                return ResourceManager.GetString("ID_LENGTH_WU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load.
        /// </summary>
        internal static string ID_LOAD {
            get {
                return ResourceManager.GetString("ID_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load dimensions ({0}).
        /// </summary>
        internal static string ID_LOADDIMENSIONS {
            get {
                return ResourceManager.GetString("ID_LOADDIMENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load height.
        /// </summary>
        internal static string ID_LOADHEIGHT {
            get {
                return ResourceManager.GetString("ID_LOADHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load weight.
        /// </summary>
        internal static string ID_LOADWEIGHT {
            get {
                return ResourceManager.GetString("ID_LOADWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load weight ({0}).
        /// </summary>
        internal static string ID_LOADWEIGHT_WU {
            get {
                return ResourceManager.GetString("ID_LOADWEIGHT_WU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum case weight should exceed {0} {1}..
        /// </summary>
        internal static string ID_MAXIMUMCASEWEIGHTSHOULDEXCEED {
            get {
                return ResourceManager.GetString("ID_MAXIMUMCASEWEIGHTSHOULDEXCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum space ({0}).
        /// </summary>
        internal static string ID_MAXIMUMSPACE {
            get {
                return ResourceManager.GetString("ID_MAXIMUMSPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inconsistency:Maximum {0} is lower than minimum {1}..
        /// </summary>
        internal static string ID_MAXLOWERTHANMIN {
            get {
                return ResourceManager.GetString("ID_MAXLOWERTHANMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string ID_NAME {
            get {
                return ResourceManager.GetString("ID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} named {1} already exists in database..
        /// </summary>
        internal static string ID_NAMEALREADYEXISTSINDB {
            get {
                return ResourceManager.GetString("ID_NAMEALREADYEXISTSINDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Net weight ({0}).
        /// </summary>
        internal static string ID_NETWEIGHT_WU {
            get {
                return ResourceManager.GetString("ID_NETWEIGHT_WU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No case selected!.
        /// </summary>
        internal static string ID_NOCASESELECTED {
            get {
                return ResourceManager.GetString("ID_NOCASESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyses.
        /// </summary>
        internal static string ID_NODE_ANALYSES {
            get {
                return ResourceManager.GetString("ID_NODE_ANALYSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Boxes.
        /// </summary>
        internal static string ID_NODE_BOXES {
            get {
                return ResourceManager.GetString("ID_NODE_BOXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bundles.
        /// </summary>
        internal static string ID_NODE_BUNDLES {
            get {
                return ResourceManager.GetString("ID_NODE_BUNDLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cases.
        /// </summary>
        internal static string ID_NODE_CASES {
            get {
                return ResourceManager.GetString("ID_NODE_CASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cylinders.
        /// </summary>
        internal static string ID_NODE_CYLINDERS {
            get {
                return ResourceManager.GetString("ID_NODE_CYLINDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interlayers.
        /// </summary>
        internal static string ID_NODE_INTERLAYERS {
            get {
                return ResourceManager.GetString("ID_NODE_INTERLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Packs.
        /// </summary>
        internal static string ID_NODE_PACKS {
            get {
                return ResourceManager.GetString("ID_NODE_PACKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pallet caps.
        /// </summary>
        internal static string ID_NODE_PALLETCAPS {
            get {
                return ResourceManager.GetString("ID_NODE_PALLETCAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pallet corners.
        /// </summary>
        internal static string ID_NODE_PALLETCORNERS {
            get {
                return ResourceManager.GetString("ID_NODE_PALLETCORNERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pallet films.
        /// </summary>
        internal static string ID_NODE_PALLETFILMS {
            get {
                return ResourceManager.GetString("ID_NODE_PALLETFILMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pallets.
        /// </summary>
        internal static string ID_NODE_PALLETS {
            get {
                return ResourceManager.GetString("ID_NODE_PALLETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trucks.
        /// </summary>
        internal static string ID_NODE_TRUCKS {
            get {
                return ResourceManager.GetString("ID_NODE_TRUCKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No orientation selected!.
        /// </summary>
        internal static string ID_NOORIENTATIONSELECTED {
            get {
                return ResourceManager.GetString("ID_NOORIENTATIONSELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No pallet solution selected.
        /// </summary>
        internal static string ID_NOPALLETSOLUTIONSELECTED {
            get {
                return ResourceManager.GetString("ID_NOPALLETSOLUTIONSELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number.
        /// </summary>
        internal static string ID_NUMBER {
            get {
                return ResourceManager.GetString("ID_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options\\Debugging.
        /// </summary>
        internal static string ID_OPTIONSDEBUGGING {
            get {
                return ResourceManager.GetString("ID_OPTIONSDEBUGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options\\Dimensions\\Case/Pallet.
        /// </summary>
        internal static string ID_OPTIONSDIMENSIONS {
            get {
                return ResourceManager.GetString("ID_OPTIONSDIMENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options\\Language &amp; Unit system.
        /// </summary>
        internal static string ID_OPTIONSMEASUREMENTSYSTEM {
            get {
                return ResourceManager.GetString("ID_OPTIONSMEASUREMENTSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options\\Pallet edition.
        /// </summary>
        internal static string ID_OPTIONSPALLETEDITION {
            get {
                return ResourceManager.GetString("ID_OPTIONSPALLETEDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options\\Plugins.
        /// </summary>
        internal static string ID_OPTIONSPLUGINS {
            get {
                return ResourceManager.GetString("ID_OPTIONSPLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options\\Reporting.
        /// </summary>
        internal static string ID_OPTIONSREPORTING {
            get {
                return ResourceManager.GetString("ID_OPTIONSREPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Orientation.
        /// </summary>
        internal static string ID_ORIENTATION {
            get {
                return ResourceManager.GetString("ID_ORIENTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Outer dimensions ({0}).
        /// </summary>
        internal static string ID_OUTERDIMENSIONS {
            get {
                return ResourceManager.GetString("ID_OUTERDIMENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pack.
        /// </summary>
        internal static string ID_PACK {
            get {
                return ResourceManager.GetString("ID_PACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à # Packs.
        /// </summary>
        internal static string ID_PACKCOUNT {
            get {
                return ResourceManager.GetString("ID_PACKCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pallet.
        /// </summary>
        internal static string ID_PALLET {
            get {
                return ResourceManager.GetString("ID_PALLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cap.
        /// </summary>
        internal static string ID_PALLETCAP {
            get {
                return ResourceManager.GetString("ID_PALLETCAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pallet cap length should exceed pallet length + overhang X....
        /// </summary>
        internal static string ID_PALLETCAPNOTLONGENOUGH {
            get {
                return ResourceManager.GetString("ID_PALLETCAPNOTLONGENOUGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pallet cap width should exceed pallet width + overhang Y....
        /// </summary>
        internal static string ID_PALLETCAPNOTWIDEENOUGH {
            get {
                return ResourceManager.GetString("ID_PALLETCAPNOTWIDEENOUGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pallet caps.
        /// </summary>
        internal static string ID_PALLETCAPS {
            get {
                return ResourceManager.GetString("ID_PALLETCAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit pallet {0}....
        /// </summary>
        internal static string ID_PALLETCAPTIONEDIT {
            get {
                return ResourceManager.GetString("ID_PALLETCAPTIONEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Corners.
        /// </summary>
        internal static string ID_PALLETCORNERS {
            get {
                return ResourceManager.GetString("ID_PALLETCORNERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pallet count.
        /// </summary>
        internal static string ID_PALLETCOUNT {
            get {
                return ResourceManager.GetString("ID_PALLETCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Film.
        /// </summary>
        internal static string ID_PALLETFILM {
            get {
                return ResourceManager.GetString("ID_PALLETFILM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pallet films.
        /// </summary>
        internal static string ID_PALLETFILMS {
            get {
                return ResourceManager.GetString("ID_PALLETFILMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pallet height
        ///({0}).
        /// </summary>
        internal static string ID_PALLETHEIGHT {
            get {
                return ResourceManager.GetString("ID_PALLETHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Limit reached.
        /// </summary>
        internal static string ID_PALLETLIMIT {
            get {
                return ResourceManager.GetString("ID_PALLETLIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Height.
        /// </summary>
        internal static string ID_PALLETMAXHEIGHT {
            get {
                return ResourceManager.GetString("ID_PALLETMAXHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number.
        /// </summary>
        internal static string ID_PALLETMAXNUMBER {
            get {
                return ResourceManager.GetString("ID_PALLETMAXNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weight.
        /// </summary>
        internal static string ID_PALLETMAXWEIGHT {
            get {
                return ResourceManager.GetString("ID_PALLETMAXWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pallets.
        /// </summary>
        internal static string ID_PALLETS {
            get {
                return ResourceManager.GetString("ID_PALLETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pallet weight
        ///({0}).
        /// </summary>
        internal static string ID_PALLETWEIGHT {
            get {
                return ResourceManager.GetString("ID_PALLETWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ready.
        /// </summary>
        internal static string ID_READY {
            get {
                return ResourceManager.GetString("ID_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User count = {0}.
        /// </summary>
        internal static string ID_REGISTEREDUSERCOUNT {
            get {
                return ResourceManager.GetString("ID_REGISTEREDUSERCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Removing existing type {0}....
        /// </summary>
        internal static string ID_REMOVINGEXISTINGTYPE {
            get {
                return ResourceManager.GetString("ID_REMOVINGEXISTINGTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save file {0}?.
        /// </summary>
        internal static string ID_SAVEMODIFIEDFILE {
            get {
                return ResourceManager.GetString("ID_SAVEMODIFIEDFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select.
        /// </summary>
        internal static string ID_SELECT {
            get {
                return ResourceManager.GetString("ID_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select at leat one layer.
        /// </summary>
        internal static string ID_SELECTATLEASTONELAYOUT {
            get {
                return ResourceManager.GetString("ID_SELECTATLEASTONELAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected.
        /// </summary>
        internal static string ID_SELECTED {
            get {
                return ResourceManager.GetString("ID_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected layer: {0} .
        /// </summary>
        internal static string ID_SELECTEDLAYER {
            get {
                return ResourceManager.GetString("ID_SELECTEDLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send to database.
        /// </summary>
        internal static string ID_SENDTODATABASE {
            get {
                return ResourceManager.GetString("ID_SENDTODATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spaces ({0}).
        /// </summary>
        internal static string ID_SPACES_WU {
            get {
                return ResourceManager.GetString("ID_SPACES_WU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Canceled!.
        /// </summary>
        internal static string ID_TASKCANCELED {
            get {
                return ResourceManager.GetString("ID_TASKCANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thickness ({0}).
        /// </summary>
        internal static string ID_THICKNESS_WU {
            get {
                return ResourceManager.GetString("ID_THICKNESS_WU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total weight ({0}).
        /// </summary>
        internal static string ID_TOTALWEIGHT_WU {
            get {
                return ResourceManager.GetString("ID_TOTALWEIGHT_WU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use transparency.
        /// </summary>
        internal static string ID_TRANSPARENCY {
            get {
                return ResourceManager.GetString("ID_TRANSPARENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Truck.
        /// </summary>
        internal static string ID_TRUCK {
            get {
                return ResourceManager.GetString("ID_TRUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unexpected type: {0}.
        /// </summary>
        internal static string ID_UNEXPECTEDTYPE {
            get {
                return ResourceManager.GetString("ID_UNEXPECTEDTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unit system....
        /// </summary>
        internal static string ID_UNITSYSTEM {
            get {
                return ResourceManager.GetString("ID_UNITSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unselect solution {0}.
        /// </summary>
        internal static string ID_UNSELECTSOLUTION {
            get {
                return ResourceManager.GetString("ID_UNSELECTSOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Define at least one stop stacking criterion.
        /// </summary>
        internal static string ID_USEATLEASTONESTOPSTACKINGCRITERION {
            get {
                return ResourceManager.GetString("ID_USEATLEASTONESTOPSTACKINGCRITERION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use transparency and/or hatching.
        /// </summary>
        internal static string ID_USETRANSPARENCYORHATCHING {
            get {
                return ResourceManager.GetString("ID_USETRANSPARENCYORHATCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version : {0}.
        /// </summary>
        internal static string ID_VERSION {
            get {
                return ResourceManager.GetString("ID_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Efficiency (%).
        /// </summary>
        internal static string ID_VOLUMEEFFICIENCY {
            get {
                return ResourceManager.GetString("ID_VOLUMEEFFICIENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weight.
        /// </summary>
        internal static string ID_WEIGHT {
            get {
                return ResourceManager.GetString("ID_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weight ({0}).
        /// </summary>
        internal static string ID_WEIGHT_WU {
            get {
                return ResourceManager.GetString("ID_WEIGHT_WU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Width.
        /// </summary>
        internal static string ID_WIDTH {
            get {
                return ResourceManager.GetString("ID_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Width ({0}).
        /// </summary>
        internal static string ID_WIDTH_WU {
            get {
                return ResourceManager.GetString("ID_WIDTH_WU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image {
            get {
                object obj = ResourceManager.GetObject("Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Interlayer {
            get {
                object obj = ResourceManager.GetObject("Interlayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OptimalCase {
            get {
                object obj = ResourceManager.GetObject("OptimalCase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pallet {
            get {
                object obj = ResourceManager.GetObject("Pallet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        internal static System.Drawing.Icon treeDim {
            get {
                object obj = ResourceManager.GetObject("treeDim", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Truck {
            get {
                object obj = ResourceManager.GetObject("Truck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap View_1 {
            get {
                object obj = ResourceManager.GetObject("View_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap View_2 {
            get {
                object obj = ResourceManager.GetObject("View_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap View_3 {
            get {
                object obj = ResourceManager.GetObject("View_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap View_4 {
            get {
                object obj = ResourceManager.GetObject("View_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap View_Top {
            get {
                object obj = ResourceManager.GetObject("View_Top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap View0 {
            get {
                object obj = ResourceManager.GetObject("View0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap View180 {
            get {
                object obj = ResourceManager.GetObject("View180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap View270 {
            get {
                object obj = ResourceManager.GetObject("View270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap View90 {
            get {
                object obj = ResourceManager.GetObject("View90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
