//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace treeDiM.StackBuilder.Desktop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::treeDiM.StackBuilder.Desktop.WindowSettings FormMainPosition {
            get {
                return ((global::treeDiM.StackBuilder.Desktop.WindowSettings)(this["FormMainPosition"]));
            }
            set {
                this["FormMainPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::treeDiM.StackBuilder.Desktop.WindowSettings FormNewDocumentPosition {
            get {
                return ((global::treeDiM.StackBuilder.Desktop.WindowSettings)(this["FormNewDocumentPosition"]));
            }
            set {
                this["FormNewDocumentPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::treeDiM.StackBuilder.Desktop.WindowSettings FormNewBoxPosition {
            get {
                return ((global::treeDiM.StackBuilder.Desktop.WindowSettings)(this["FormNewBoxPosition"]));
            }
            set {
                this["FormNewBoxPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::treeDiM.StackBuilder.Desktop.WindowSettings FormNewPalletPosition {
            get {
                return ((global::treeDiM.StackBuilder.Desktop.WindowSettings)(this["FormNewPalletPosition"]));
            }
            set {
                this["FormNewPalletPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::treeDiM.StackBuilder.Desktop.WindowSettings FormNewInterlayerPosition {
            get {
                return ((global::treeDiM.StackBuilder.Desktop.WindowSettings)(this["FormNewInterlayerPosition"]));
            }
            set {
                this["FormNewInterlayerPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::treeDiM.StackBuilder.Desktop.WindowSettings FormNewBundlePosition {
            get {
                return ((global::treeDiM.StackBuilder.Desktop.WindowSettings)(this["FormNewBundlePosition"]));
            }
            set {
                this["FormNewBundlePosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DocumentAuthor {
            get {
                return ((string)(this["DocumentAuthor"]));
            }
            set {
                this["DocumentAuthor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowAlignedLayer {
            get {
                return ((bool)(this["AllowAlignedLayer"]));
            }
            set {
                this["AllowAlignedLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowAlternateLayer {
            get {
                return ((bool)(this["AllowAlternateLayer"]));
            }
            set {
                this["AllowAlternateLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AllowedPatterns {
            get {
                return ((string)(this["AllowedPatterns"]));
            }
            set {
                this["AllowedPatterns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::treeDiM.StackBuilder.Desktop.WindowSettings FormNewAnalysis {
            get {
                return ((global::treeDiM.StackBuilder.Desktop.WindowSettings)(this["FormNewAnalysis"]));
            }
            set {
                this["FormNewAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowVerticalX {
            get {
                return ((bool)(this["AllowVerticalX"]));
            }
            set {
                this["AllowVerticalX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowVerticalY {
            get {
                return ((bool)(this["AllowVerticalY"]));
            }
            set {
                this["AllowVerticalY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowVerticalZ {
            get {
                return ((bool)(this["AllowVerticalZ"]));
            }
            set {
                this["AllowVerticalZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PalletOverhangLength {
            get {
                return ((int)(this["PalletOverhangLength"]));
            }
            set {
                this["PalletOverhangLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PalletOverhangWidth {
            get {
                return ((int)(this["PalletOverhangWidth"]));
            }
            set {
                this["PalletOverhangWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::treeDiM.StackBuilder.Desktop.WindowSettings FormNewTruckPosition {
            get {
                return ((global::treeDiM.StackBuilder.Desktop.WindowSettings)(this["FormNewTruckPosition"]));
            }
            set {
                this["FormNewTruckPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::treeDiM.StackBuilder.Desktop.WindowSettings FormNewAnalysisPosition {
            get {
                return ((global::treeDiM.StackBuilder.Desktop.WindowSettings)(this["FormNewAnalysisPosition"]));
            }
            set {
                this["FormNewAnalysisPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::treeDiM.StackBuilder.Desktop.WindowSettings FormNewBundleAnalysisPosition {
            get {
                return ((global::treeDiM.StackBuilder.Desktop.WindowSettings)(this["FormNewBundleAnalysisPosition"]));
            }
            set {
                this["FormNewBundleAnalysisPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KeepBestSolutions {
            get {
                return ((bool)(this["KeepBestSolutions"]));
            }
            set {
                this["KeepBestSolutions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int NoSolutionsToKeep {
            get {
                return ((int)(this["NoSolutionsToKeep"]));
            }
            set {
                this["NoSolutionsToKeep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::treeDiM.StackBuilder.Desktop.WindowSettings FormNewTruckAnalysisPosition {
            get {
                return ((global::treeDiM.StackBuilder.Desktop.WindowSettings)(this["FormNewTruckAnalysisPosition"]));
            }
            set {
                this["FormNewTruckAnalysisPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowSeveralPalletLayers {
            get {
                return ((bool)(this["AllowSeveralPalletLayers"]));
            }
            set {
                this["AllowSeveralPalletLayers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowPalletOrientationX {
            get {
                return ((bool)(this["AllowPalletOrientationX"]));
            }
            set {
                this["AllowPalletOrientationX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowPalletOrientationY {
            get {
                return ((bool)(this["AllowPalletOrientationY"]));
            }
            set {
                this["AllowPalletOrientationY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinDistancePalletTruckWallX {
            get {
                return ((double)(this["MinDistancePalletTruckWallX"]));
            }
            set {
                this["MinDistancePalletTruckWallX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinDistancePalletTruckRoof {
            get {
                return ((double)(this["MinDistancePalletTruckRoof"]));
            }
            set {
                this["MinDistancePalletTruckRoof"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::treeDiM.StackBuilder.Desktop.WindowSettings FormNewCaseAnalysisPosition {
            get {
                return ((global::treeDiM.StackBuilder.Desktop.WindowSettings)(this["FormNewCaseAnalysisPosition"]));
            }
            set {
                this["FormNewCaseAnalysisPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowVerticalX_CaseAnalysis {
            get {
                return ((bool)(this["AllowVerticalX_CaseAnalysis"]));
            }
            set {
                this["AllowVerticalX_CaseAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowVerticalY_CaseAnalysis {
            get {
                return ((bool)(this["AllowVerticalY_CaseAnalysis"]));
            }
            set {
                this["AllowVerticalY_CaseAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowVerticalZ_CaseAnalysis {
            get {
                return ((bool)(this["AllowVerticalZ_CaseAnalysis"]));
            }
            set {
                this["AllowVerticalZ_CaseAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AllowedPatterns_CaseAnalysis {
            get {
                return ((string)(this["AllowedPatterns_CaseAnalysis"]));
            }
            set {
                this["AllowedPatterns_CaseAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowAlignedLayer_CaseAnalysis {
            get {
                return ((bool)(this["AllowAlignedLayer_CaseAnalysis"]));
            }
            set {
                this["AllowAlignedLayer_CaseAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowAlternateLayer_CaseAnalysis {
            get {
                return ((bool)(this["AllowAlternateLayer_CaseAnalysis"]));
            }
            set {
                this["AllowAlternateLayer_CaseAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPalletSolution_CaseAnalysis {
            get {
                return ((bool)(this["ShowPalletSolution_CaseAnalysis"]));
            }
            set {
                this["ShowPalletSolution_CaseAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double OverhangX {
            get {
                return ((double)(this["OverhangX"]));
            }
            set {
                this["OverhangX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double OverhangY {
            get {
                return ((double)(this["OverhangY"]));
            }
            set {
                this["OverhangY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::treeDiM.StackBuilder.Desktop.WindowSettings FormEditBitmapsPosition {
            get {
                return ((global::treeDiM.StackBuilder.Desktop.WindowSettings)(this["FormEditBitmapsPosition"]));
            }
            set {
                this["FormEditBitmapsPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowImagesPallet {
            get {
                return ((bool)(this["ShowImagesPallet"]));
            }
            set {
                this["ShowImagesPallet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowImagesTrue {
            get {
                return ((bool)(this["ShowImagesTrue"]));
            }
            set {
                this["ShowImagesTrue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowImagesCase {
            get {
                return ((bool)(this["ShowImagesCase"]));
            }
            set {
                this["ShowImagesCase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int NumberWallsLength {
            get {
                return ((int)(this["NumberWallsLength"]));
            }
            set {
                this["NumberWallsLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int NumberWallsWidth {
            get {
                return ((int)(this["NumberWallsWidth"]));
            }
            set {
                this["NumberWallsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int NumberWallsHeight {
            get {
                return ((int)(this["NumberWallsHeight"]));
            }
            set {
                this["NumberWallsHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double WallThickness {
            get {
                return ((double)(this["WallThickness"]));
            }
            set {
                this["WallThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double WallSurfaceMass {
            get {
                return ((double)(this["WallSurfaceMass"]));
            }
            set {
                this["WallSurfaceMass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int NumberBoxesPerCase {
            get {
                return ((int)(this["NumberBoxesPerCase"]));
            }
            set {
                this["NumberBoxesPerCase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public double PalletHeight {
            get {
                return ((double)(this["PalletHeight"]));
            }
            set {
                this["PalletHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::treeDiM.StackBuilder.Desktop.WindowSettings FormOptimizeCasePosition {
            get {
                return ((global::treeDiM.StackBuilder.Desktop.WindowSettings)(this["FormOptimizeCasePosition"]));
            }
            set {
                this["FormOptimizeCasePosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::treeDiM.StackBuilder.Desktop.WindowSettings FormNewCaseOfBoxesPosition {
            get {
                return ((global::treeDiM.StackBuilder.Desktop.WindowSettings)(this["FormNewCaseOfBoxesPosition"]));
            }
            set {
                this["FormNewCaseOfBoxesPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ForceVerticalBoxOrientation {
            get {
                return ((bool)(this["ForceVerticalBoxOrientation"]));
            }
            set {
                this["ForceVerticalBoxOrientation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EUR")]
        public string PalletTypeName {
            get {
                return ((string)(this["PalletTypeName"]));
            }
            set {
                this["PalletTypeName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\PalletSolutionsDB\\")]
        public string PalletSolutionsPath {
            get {
                return ((string)(this["PalletSolutionsPath"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowStartPage {
            get {
                return ((bool)(this["ShowStartPage"]));
            }
            set {
                this["ShowStartPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReportInitialDirectory {
            get {
                return ((string)(this["ReportInitialDirectory"]));
            }
            set {
                this["ReportInitialDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowLayerOrientChange {
            get {
                return ((bool)(this["AllowLayerOrientChange"]));
            }
            set {
                this["AllowLayerOrientChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowLayerOrientChangeLastOnly {
            get {
                return ((bool)(this["AllowLayerOrientChangeLastOnly"]));
            }
            set {
                this["AllowLayerOrientChangeLastOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReporterImageSize {
            get {
                return ((int)(this["ReporterImageSize"]));
            }
            set {
                this["ReporterImageSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UnitSystem {
            get {
                return ((int)(this["UnitSystem"]));
            }
            set {
                this["UnitSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludeCaseAsBoxes {
            get {
                return ((bool)(this["IncludeCaseAsBoxes"]));
            }
            set {
                this["IncludeCaseAsBoxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CultureToUse {
            get {
                return ((string)(this["CultureToUse"]));
            }
            set {
                this["CultureToUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1700")]
        public double MaximumPalletHeight {
            get {
                return ((double)(this["MaximumPalletHeight"]));
            }
            set {
                this["MaximumPalletHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double MaximumPalletWeight {
            get {
                return ((double)(this["MaximumPalletWeight"]));
            }
            set {
                this["MaximumPalletWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("K:\\GitHub\\StackBuilder\\Samples\\SampleBook.xls")]
        public string ExcelLibraryPath {
            get {
                return ((string)(this["ExcelLibraryPath"]));
            }
            set {
                this["ExcelLibraryPath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.treedim.com/stackbuilder/")]
        public string StartPageUrl {
            get {
                return ((string)(this["StartPageUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CloseDbBrowserAfterImport {
            get {
                return ((bool)(this["CloseDbBrowserAfterImport"]));
            }
            set {
                this["CloseDbBrowserAfterImport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.treedim.com/stackbuilder/en/documentation/user-guide/")]
        public string HelpPageUrl {
            get {
                return ((string)(this["HelpPageUrl"]));
            }
            set {
                this["HelpPageUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WrapperType {
            get {
                return ((int)(this["WrapperType"]));
            }
            set {
                this["WrapperType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinDistancePalletTruckWallY {
            get {
                return ((double)(this["MinDistancePalletTruckWallY"]));
            }
            set {
                this["MinDistancePalletTruckWallY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowMultipleLayers {
            get {
                return ((bool)(this["AllowMultipleLayers"]));
            }
            set {
                this["AllowMultipleLayers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PluginPath {
            get {
                return ((string)(this["PluginPath"]));
            }
            set {
                this["PluginPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int GridFontSize {
            get {
                return ((int)(this["GridFontSize"]));
            }
            set {
                this["GridFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowDisconnectedMode {
            get {
                return ((bool)(this["AllowDisconnectedMode"]));
            }
            set {
                this["AllowDisconnectedMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinCaseDimChecked {
            get {
                return ((bool)(this["MinCaseDimChecked"]));
            }
            set {
                this["MinCaseDimChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MaxCaseDimChecked {
            get {
                return ((bool)(this["MaxCaseDimChecked"]));
            }
            set {
                this["MaxCaseDimChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinCaseDimX {
            get {
                return ((double)(this["MinCaseDimX"]));
            }
            set {
                this["MinCaseDimX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinCaseDimY {
            get {
                return ((double)(this["MinCaseDimY"]));
            }
            set {
                this["MinCaseDimY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinCaseDimZ {
            get {
                return ((double)(this["MinCaseDimZ"]));
            }
            set {
                this["MinCaseDimZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double MaxCaseDimX {
            get {
                return ((double)(this["MaxCaseDimX"]));
            }
            set {
                this["MaxCaseDimX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double MaxCaseDimY {
            get {
                return ((double)(this["MaxCaseDimY"]));
            }
            set {
                this["MaxCaseDimY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double MaxCaseDimZ {
            get {
                return ((double)(this["MaxCaseDimZ"]));
            }
            set {
                this["MaxCaseDimZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DimCasePalletSol1 {
            get {
                return ((int)(this["DimCasePalletSol1"]));
            }
            set {
                this["DimCasePalletSol1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DimCasePalletSol2 {
            get {
                return ((int)(this["DimCasePalletSol2"]));
            }
            set {
                this["DimCasePalletSol2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.plmpack.com/Stackbuilder/download/Catalog.xlsx")]
        public string ExcelTemplateFileURL {
            get {
                return ((string)(this["ExcelTemplateFileURL"]));
            }
            set {
                this["ExcelTemplateFileURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double DistanceAboveSelectedLayer {
            get {
                return ((double)(this["DistanceAboveSelectedLayer"]));
            }
            set {
                this["DistanceAboveSelectedLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DummyMode {
            get {
                return ((bool)(this["DummyMode"]));
            }
            set {
                this["DummyMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int MaximumNumber {
            get {
                return ((int)(this["MaximumNumber"]));
            }
            set {
                this["MaximumNumber"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.treedim.com/")]
        public string CompanyUrl {
            get {
                return ((string)(this["CompanyUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("info@treedim.com")]
        public string EmailSupport {
            get {
                return ((string)(this["EmailSupport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.plmpack.com/packlib/ClickOnce/PLMPackLibClient.application")]
        public string UrlPLMPackLib {
            get {
                return ((string)(this["UrlPLMPackLib"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowLogConsole {
            get {
                return ((bool)(this["ShowLogConsole"]));
            }
            set {
                this["ShowLogConsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double MaximumCaseWeight {
            get {
                return ((double)(this["MaximumCaseWeight"]));
            }
            set {
                this["MaximumCaseWeight"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://plmpack.com/stackbuilder/download/AutoUpdater.xml")]
        public string AutoUpdaterXMLPath {
            get {
                return ((string)(this["AutoUpdaterXMLPath"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ExportCoordinatesMode {
            get {
                return ((int)(this["ExportCoordinatesMode"]));
            }
            set {
                this["ExportCoordinatesMode"] = value;
            }
        }
    }
}
