//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace treeDiM.StackBuilder.Basics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("treeDiM.StackBuilder.Basics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # CSU.
        /// </summary>
        internal static string ID_CONSUMERSALESUNITS {
            get {
                return ResourceManager.GetString("ID_CONSUMERSALESUNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string ID_INDEX {
            get {
                return ResourceManager.GetString("ID_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        internal static string ID_LAYER {
            get {
                return ResourceManager.GetString("ID_LAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer pattern.
        /// </summary>
        internal static string ID_LAYERPATTERN {
            get {
                return ResourceManager.GetString("ID_LAYERPATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        internal static string ID_LAYERS {
            get {
                return ResourceManager.GetString("ID_LAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers = All.
        /// </summary>
        internal static string ID_LAYERSALL {
            get {
                return ResourceManager.GetString("ID_LAYERSALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer weight.
        /// </summary>
        internal static string ID_LAYERWEIGHT {
            get {
                return ResourceManager.GetString("ID_LAYERWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded case.
        /// </summary>
        internal static string ID_LOADEDCASE {
            get {
                return ResourceManager.GetString("ID_LOADEDCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded pallet.
        /// </summary>
        internal static string ID_LOADEDPALLET {
            get {
                return ResourceManager.GetString("ID_LOADEDPALLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum space.
        /// </summary>
        internal static string ID_MAXIMUMSPACE {
            get {
                return ResourceManager.GetString("ID_MAXIMUMSPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        internal static string ID_NAMEBOX {
            get {
                return ResourceManager.GetString("ID_NAMEBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle.
        /// </summary>
        internal static string ID_NAMEBUNDLE {
            get {
                return ResourceManager.GetString("ID_NAMEBUNDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case.
        /// </summary>
        internal static string ID_NAMECASE {
            get {
                return ResourceManager.GetString("ID_NAMECASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder.
        /// </summary>
        internal static string ID_NAMECYLINDER {
            get {
                return ResourceManager.GetString("ID_NAMECYLINDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack.
        /// </summary>
        internal static string ID_NAMEPACK {
            get {
                return ResourceManager.GetString("ID_NAMEPACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet.
        /// </summary>
        internal static string ID_NAMEPALLET {
            get {
                return ResourceManager.GetString("ID_NAMEPALLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck.
        /// </summary>
        internal static string ID_NAMETRUCK {
            get {
                return ResourceManager.GetString("ID_NAMETRUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Packs.
        /// </summary>
        internal static string ID_PACKCOUNT {
            get {
                return ResourceManager.GetString("ID_PACKCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet height.
        /// </summary>
        internal static string ID_PALLETHEIGHT {
            get {
                return ResourceManager.GetString("ID_PALLETHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet weight.
        /// </summary>
        internal static string ID_PALLETWEIGHT {
            get {
                return ResourceManager.GetString("ID_PALLETWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string ID_SELECTED {
            get {
                return ResourceManager.GetString("ID_SELECTED", resourceCulture);
            }
        }
    }
}
