del /q "..\..\CustomProjects\treeDiM.StackBuilder.TechnologyBSA_ASPNET\Bin\*.pdb"
del /q "..\..\CustomProjects\treeDiM.StackBuilder.TechnologyBSA_ASPNET\Bin\*.dll.config"
del /q "..\..\CustomProjects\treeDiM.StackBuilder.TechnologyBSA_ASPNET\Bin\*.xml"
del /q "..\..\CustomProjects\treeDiM.StackBuilder.TechnologyBSA_ASPNET\Bin\*.resx"

rmdir /s /q "..\..\CustomProjects\treeDiM.StackBuilder.TechnologyBSA_ASPNET\Bin\de"
rmdir /s /q "..\..\CustomProjects\treeDiM.StackBuilder.TechnologyBSA_ASPNET\Bin\es"
rmdir /s /q "..\..\CustomProjects\treeDiM.StackBuilder.TechnologyBSA_ASPNET\Bin\fr"
rmdir /s /q "..\..\CustomProjects\treeDiM.StackBuilder.TechnologyBSA_ASPNET\Bin\it"
rmdir /s /q "..\..\CustomProjects\treeDiM.StackBuilder.TechnologyBSA_ASPNET\Bin\ja"
rmdir /s /q "..\..\CustomProjects\treeDiM.StackBuilder.TechnologyBSA_ASPNET\Bin\pl"
rmdir /s /q "..\..\CustomProjects\treeDiM.StackBuilder.TechnologyBSA_ASPNET\Bin\pt"
rmdir /s /q "..\..\CustomProjects\treeDiM.StackBuilder.TechnologyBSA_ASPNET\Bin\sv"
rmdir /s /q "..\..\CustomProjects\treeDiM.StackBuilder.TechnologyBSA_ASPNET\Bin\zh"
rmdir /s /q "..\..\CustomProjects\treeDiM.StackBuilder.TechnologyBSA_ASPNET\Bin\nl"
rmdir /s /q "..\..\CustomProjects\treeDiM.StackBuilder.TechnologyBSA_ASPNET\Bin\ru"
rmdir /s /q "..\..\CustomProjects\treeDiM.StackBuilder.TechnologyBSA_ASPNET\Bin\sl"
rmdir /s /q "..\..\CustomProjects\treeDiM.StackBuilder.TechnologyBSA_ASPNET\Bin\tr"

"C:\Program Files (x86)\WiX Toolset v3.14\bin\heat.exe" dir "..\..\CustomProjects\treeDiM.StackBuilder.TechnologyBSA_ASPNET\Bin" -dr Bin -cg CompGroup_StackBuilderTechBSABin -gg -g1 -sf -srd -sreg -var "var.StackBuilderTechBSABinSourceDir" -o ".\GroupStackBuilderTechBSA.wxs"