//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("treeDiM")]
[assembly: System.Reflection.AssemblyCopyright("Copyright ©  2018")]
[assembly: System.Reflection.AssemblyVersion("3.0.0.82")]
[assembly: System.Reflection.AssemblyFileVersion("3.0.0.82")]



