//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptionsLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OptionsForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OptionsForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OptionsLib.OptionsForm", typeof(OptionsForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes..
        /// </summary>
        public static string ApplyBtn_AccessibleDescription {
            get {
                return ResourceManager.GetString("ApplyBtn.AccessibleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Bottom, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles ApplyBtn_Anchor {
            get {
                object obj = ResourceManager.GetObject("ApplyBtn.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool ApplyBtn_Enabled {
            get {
                object obj = ResourceManager.GetObject("ApplyBtn.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=186,Y=347}.
        /// </summary>
        public static System.Drawing.Point ApplyBtn_Location {
            get {
                object obj = ResourceManager.GetObject("ApplyBtn.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size ApplyBtn_Size {
            get {
                object obj = ResourceManager.GetObject("ApplyBtn.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        public static int ApplyBtn_TabIndex {
            get {
                object obj = ResourceManager.GetObject("ApplyBtn.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&amp;pply.
        /// </summary>
        public static string ApplyBtn_Text {
            get {
                return ResourceManager.GetString("ApplyBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This box indicates that the application must restart in order for changes to take effect..
        /// </summary>
        public static string AppRestartLabel_AccessibleDescription {
            get {
                return ResourceManager.GetString("AppRestartLabel.AccessibleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        public static System.Windows.Forms.DockStyle AppRestartLabel_Dock {
            get {
                object obj = ResourceManager.GetObject("AppRestartLabel.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Arial, Size=8,25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font AppRestartLabel_Font {
            get {
                object obj = ResourceManager.GetObject("AppRestartLabel.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point AppRestartLabel_Location {
            get {
                object obj = ResourceManager.GetObject("AppRestartLabel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=52, Height=23}.
        /// </summary>
        public static System.Drawing.Size AppRestartLabel_Size {
            get {
                object obj = ResourceManager.GetObject("AppRestartLabel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int AppRestartLabel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("AppRestartLabel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application must restart for changes to take effect..
        /// </summary>
        public static string AppRestartLabel_Text {
            get {
                return ResourceManager.GetString("AppRestartLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleCenter.
        /// </summary>
        public static System.Drawing.ContentAlignment AppRestartLabel_TextAlign {
            get {
                object obj = ResourceManager.GetObject("AppRestartLabel.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel changes and close options form..
        /// </summary>
        public static string CancelBtn_AccessibleDescription {
            get {
                return ResourceManager.GetString("CancelBtn.AccessibleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Bottom, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles CancelBtn_Anchor {
            get {
                object obj = ResourceManager.GetObject("CancelBtn.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=267,Y=347}.
        /// </summary>
        public static System.Drawing.Point CancelBtn_Location {
            get {
                object obj = ResourceManager.GetObject("CancelBtn.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size CancelBtn_Size {
            get {
                object obj = ResourceManager.GetObject("CancelBtn.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int CancelBtn_TabIndex {
            get {
                object obj = ResourceManager.GetObject("CancelBtn.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        public static string CancelBtn_Text {
            get {
                return ResourceManager.GetString("CancelBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This box shows a description for each Category in the tree..
        /// </summary>
        public static string CatDescr_AccessibleDescription {
            get {
                return ResourceManager.GetString("CatDescr.AccessibleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        public static System.Windows.Forms.DockStyle CatDescr_Dock {
            get {
                object obj = ResourceManager.GetObject("CatDescr.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=8,25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font CatDescr_Font {
            get {
                object obj = ResourceManager.GetObject("CatDescr.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point CatDescr_Location {
            get {
                object obj = ResourceManager.GetObject("CatDescr.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=116, Height=35}.
        /// </summary>
        public static System.Drawing.Size CatDescr_Size {
            get {
                object obj = ResourceManager.GetObject("CatDescr.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int CatDescr_TabIndex {
            get {
                object obj = ResourceManager.GetObject("CatDescr.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description..
        /// </summary>
        public static string CatDescr_Text {
            get {
                return ResourceManager.GetString("CatDescr.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleCenter.
        /// </summary>
        public static System.Drawing.ContentAlignment CatDescr_TextAlign {
            get {
                object obj = ResourceManager.GetObject("CatDescr.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Bottom, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles CatDescrPanel_Anchor {
            get {
                object obj = ResourceManager.GetObject("CatDescrPanel.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=4,Y=339}.
        /// </summary>
        public static System.Drawing.Point CatDescrPanel_Location {
            get {
                object obj = ResourceManager.GetObject("CatDescrPanel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=0,Top=0,Right=0,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding CatDescrPanel_Margin {
            get {
                object obj = ResourceManager.GetObject("CatDescrPanel.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=118, Height=37}.
        /// </summary>
        public static System.Drawing.Size CatDescrPanel_Size {
            get {
                object obj = ResourceManager.GetObject("CatDescrPanel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int CatDescrPanel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("CatDescrPanel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool CatDescrPanel_Visible {
            get {
                object obj = ResourceManager.GetObject("CatDescrPanel.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories tree Header..
        /// </summary>
        public static string CatHeader_AccessibleDescription {
            get {
                return ResourceManager.GetString("CatHeader.AccessibleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        public static System.Windows.Forms.DockStyle CatHeader_Dock {
            get {
                object obj = ResourceManager.GetObject("CatHeader.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9,75, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font CatHeader_Font {
            get {
                object obj = ResourceManager.GetObject("CatHeader.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point CatHeader_Location {
            get {
                object obj = ResourceManager.GetObject("CatHeader.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=119, Height=32}.
        /// </summary>
        public static System.Drawing.Size CatHeader_Size {
            get {
                object obj = ResourceManager.GetObject("CatHeader.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int CatHeader_TabIndex {
            get {
                object obj = ResourceManager.GetObject("CatHeader.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories:.
        /// </summary>
        public static string CatHeader_Text {
            get {
                return ResourceManager.GetString("CatHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleCenter.
        /// </summary>
        public static System.Drawing.ContentAlignment CatHeader_TextAlign {
            get {
                object obj = ResourceManager.GetObject("CatHeader.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles CatHeaderPanel_Anchor {
            get {
                object obj = ResourceManager.GetObject("CatHeaderPanel.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=3}.
        /// </summary>
        public static System.Drawing.Point CatHeaderPanel_Location {
            get {
                object obj = ResourceManager.GetObject("CatHeaderPanel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=0,Top=0,Right=0,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding CatHeaderPanel_Margin {
            get {
                object obj = ResourceManager.GetObject("CatHeaderPanel.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=119, Height=32}.
        /// </summary>
        public static System.Drawing.Size CatHeaderPanel_Size {
            get {
                object obj = ResourceManager.GetObject("CatHeaderPanel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int CatHeaderPanel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("CatHeaderPanel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool CatHeaderPanel_Visible {
            get {
                object obj = ResourceManager.GetObject("CatHeaderPanel.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options Categories..
        /// </summary>
        public static string CatTree_AccessibleDescription {
            get {
                return ResourceManager.GetString("CatTree.AccessibleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        public static System.Windows.Forms.DockStyle CatTree_Dock {
            get {
                object obj = ResourceManager.GetObject("CatTree.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point CatTree_Location {
            get {
                object obj = ResourceManager.GetObject("CatTree.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=119, Height=300}.
        /// </summary>
        public static System.Drawing.Size CatTree_Size {
            get {
                object obj = ResourceManager.GetObject("CatTree.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int CatTree_TabIndex {
            get {
                object obj = ResourceManager.GetObject("CatTree.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles CatTreePanel_Anchor {
            get {
                object obj = ResourceManager.GetObject("CatTreePanel.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=37}.
        /// </summary>
        public static System.Drawing.Point CatTreePanel_Location {
            get {
                object obj = ResourceManager.GetObject("CatTreePanel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=0,Top=0,Right=0,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding CatTreePanel_Margin {
            get {
                object obj = ResourceManager.GetObject("CatTreePanel.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=119, Height=300}.
        /// </summary>
        public static System.Drawing.Size CatTreePanel_Size {
            get {
                object obj = ResourceManager.GetObject("CatTreePanel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int CatTreePanel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("CatTreePanel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        public static System.Windows.Forms.DockStyle DescriptionPanel_Dock {
            get {
                object obj = ResourceManager.GetObject("DescriptionPanel.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point DescriptionPanel_Location {
            get {
                object obj = ResourceManager.GetObject("DescriptionPanel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=340, Height=69}.
        /// </summary>
        public static System.Drawing.Size DescriptionPanel_Size {
            get {
                object obj = ResourceManager.GetObject("DescriptionPanel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        public static int DescriptionPanel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("DescriptionPanel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Bottom, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles label2_Anchor {
            get {
                object obj = ResourceManager.GetObject("label2.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=339}.
        /// </summary>
        public static System.Drawing.Point label2_Location {
            get {
                object obj = ResourceManager.GetObject("label2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=10,Top=0,Right=10,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding label2_Margin {
            get {
                object obj = ResourceManager.GetObject("label2.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=339, Height=2}.
        /// </summary>
        public static System.Drawing.Size label2_Size {
            get {
                object obj = ResourceManager.GetObject("label2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int label2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes and close the options form..
        /// </summary>
        public static string OKBtn_AccessibleDescription {
            get {
                return ResourceManager.GetString("OKBtn.AccessibleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Bottom, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles OKBtn_Anchor {
            get {
                object obj = ResourceManager.GetObject("OKBtn.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=105,Y=347}.
        /// </summary>
        public static System.Drawing.Point OKBtn_Location {
            get {
                object obj = ResourceManager.GetObject("OKBtn.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size OKBtn_Size {
            get {
                object obj = ResourceManager.GetObject("OKBtn.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int OKBtn_TabIndex {
            get {
                object obj = ResourceManager.GetObject("OKBtn.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        public static string OKBtn_Text {
            get {
                return ResourceManager.GetString("OKBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        public static System.Windows.Forms.DockStyle OptDescrSplit_Dock {
            get {
                object obj = ResourceManager.GetObject("OptDescrSplit.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool OptDescrSplit_IsSplitterFixed {
            get {
                object obj = ResourceManager.GetObject("OptDescrSplit.IsSplitterFixed", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point OptDescrSplit_Location {
            get {
                object obj = ResourceManager.GetObject("OptDescrSplit.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=0,Top=0,Right=0,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding OptDescrSplit_Margin {
            get {
                object obj = ResourceManager.GetObject("OptDescrSplit.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=0, Height=64}.
        /// </summary>
        public static System.Drawing.Size OptDescrSplit_MaximumSize {
            get {
                object obj = ResourceManager.GetObject("OptDescrSplit.MaximumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Orientation similar to Horizontal.
        /// </summary>
        public static System.Windows.Forms.Orientation OptDescrSplit_Orientation {
            get {
                object obj = ResourceManager.GetObject("OptDescrSplit.Orientation", resourceCulture);
                return ((System.Windows.Forms.Orientation)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 35.
        /// </summary>
        public static int OptDescrSplit_Panel1MinSize {
            get {
                object obj = ResourceManager.GetObject("OptDescrSplit.Panel1MinSize", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 17.
        /// </summary>
        public static int OptDescrSplit_Panel2MinSize {
            get {
                object obj = ResourceManager.GetObject("OptDescrSplit.Panel2MinSize", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=340, Height=64}.
        /// </summary>
        public static System.Drawing.Size OptDescrSplit_Size {
            get {
                object obj = ResourceManager.GetObject("OptDescrSplit.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 46.
        /// </summary>
        public static int OptDescrSplit_SplitterDistance {
            get {
                object obj = ResourceManager.GetObject("OptDescrSplit.SplitterDistance", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int OptDescrSplit_SplitterWidth {
            get {
                object obj = ResourceManager.GetObject("OptDescrSplit.SplitterWidth", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int OptDescrSplit_TabIndex {
            get {
                object obj = ResourceManager.GetObject("OptDescrSplit.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This box shows a short description for each control..
        /// </summary>
        public static string OptionDescrLabel_AccessibleDescription {
            get {
                return ResourceManager.GetString("OptionDescrLabel.AccessibleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        public static System.Windows.Forms.DockStyle OptionDescrLabel_Dock {
            get {
                object obj = ResourceManager.GetObject("OptionDescrLabel.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point OptionDescrLabel_Location {
            get {
                object obj = ResourceManager.GetObject("OptionDescrLabel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=338, Height=62}.
        /// </summary>
        public static System.Drawing.Size OptionDescrLabel_Size {
            get {
                object obj = ResourceManager.GetObject("OptionDescrLabel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int OptionDescrLabel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("OptionDescrLabel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description..
        /// </summary>
        public static string OptionDescrLabel_Text {
            get {
                return ResourceManager.GetString("OptionDescrLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleCenter.
        /// </summary>
        public static System.Drawing.ContentAlignment OptionDescrLabel_TextAlign {
            get {
                object obj = ResourceManager.GetObject("OptionDescrLabel.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool OptionPanelContainer_AutoScroll {
            get {
                object obj = ResourceManager.GetObject("OptionPanelContainer.AutoScroll", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        public static System.Windows.Forms.DockStyle OptionPanelContainer_Dock {
            get {
                object obj = ResourceManager.GetObject("OptionPanelContainer.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point OptionPanelContainer_Location {
            get {
                object obj = ResourceManager.GetObject("OptionPanelContainer.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=0,Top=0,Right=0,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding OptionPanelContainer_Margin {
            get {
                object obj = ResourceManager.GetObject("OptionPanelContainer.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=340, Height=215}.
        /// </summary>
        public static System.Drawing.Size OptionPanelContainer_MinimumSize {
            get {
                object obj = ResourceManager.GetObject("OptionPanelContainer.MinimumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=340, Height=215}.
        /// </summary>
        public static System.Drawing.Size OptionPanelContainer_Size {
            get {
                object obj = ResourceManager.GetObject("OptionPanelContainer.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int OptionPanelContainer_TabIndex {
            get {
                object obj = ResourceManager.GetObject("OptionPanelContainer.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        public static System.Windows.Forms.DockStyle OptionsFormSplit_Dock {
            get {
                object obj = ResourceManager.GetObject("OptionsFormSplit.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool OptionsFormSplit_IsSplitterFixed {
            get {
                object obj = ResourceManager.GetObject("OptionsFormSplit.IsSplitterFixed", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point OptionsFormSplit_Location {
            get {
                object obj = ResourceManager.GetObject("OptionsFormSplit.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=0,Top=0,Right=0,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding OptionsFormSplit_Margin {
            get {
                object obj = ResourceManager.GetObject("OptionsFormSplit.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=480, Height=375}.
        /// </summary>
        public static System.Drawing.Size OptionsFormSplit_MinimumSize {
            get {
                object obj = ResourceManager.GetObject("OptionsFormSplit.MinimumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 125.
        /// </summary>
        public static int OptionsFormSplit_Panel1MinSize {
            get {
                object obj = ResourceManager.GetObject("OptionsFormSplit.Panel1MinSize", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 350.
        /// </summary>
        public static int OptionsFormSplit_Panel2MinSize {
            get {
                object obj = ResourceManager.GetObject("OptionsFormSplit.Panel2MinSize", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=480, Height=379}.
        /// </summary>
        public static System.Drawing.Size OptionsFormSplit_Size {
            get {
                object obj = ResourceManager.GetObject("OptionsFormSplit.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 125.
        /// </summary>
        public static int OptionsFormSplit_SplitterDistance {
            get {
                object obj = ResourceManager.GetObject("OptionsFormSplit.SplitterDistance", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int OptionsFormSplit_SplitterWidth {
            get {
                object obj = ResourceManager.GetObject("OptionsFormSplit.SplitterWidth", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int OptionsFormSplit_TabIndex {
            get {
                object obj = ResourceManager.GetObject("OptionsFormSplit.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This box shows the options path for the current options panel..
        /// </summary>
        public static string OptionsPanelPath_AccessibleDescription {
            get {
                return ResourceManager.GetString("OptionsPanelPath.AccessibleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles OptionsPanelPath_Anchor {
            get {
                object obj = ResourceManager.GetObject("OptionsPanelPath.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Verdana, Size=11,25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font OptionsPanelPath_Font {
            get {
                object obj = ResourceManager.GetObject("OptionsPanelPath.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=3}.
        /// </summary>
        public static System.Drawing.Point OptionsPanelPath_Location {
            get {
                object obj = ResourceManager.GetObject("OptionsPanelPath.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=10,Top=6,Right=0,Bottom=6}.
        /// </summary>
        public static System.Windows.Forms.Padding OptionsPanelPath_Padding {
            get {
                object obj = ResourceManager.GetObject("OptionsPanelPath.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=339, Height=32}.
        /// </summary>
        public static System.Drawing.Size OptionsPanelPath_Size {
            get {
                object obj = ResourceManager.GetObject("OptionsPanelPath.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 8.
        /// </summary>
        public static int OptionsPanelPath_TabIndex {
            get {
                object obj = ResourceManager.GetObject("OptionsPanelPath.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options » Path.
        /// </summary>
        public static string OptionsPanelPath_Text {
            get {
                return ResourceManager.GetString("OptionsPanelPath.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleLeft.
        /// </summary>
        public static System.Drawing.ContentAlignment OptionsPanelPath_TextAlign {
            get {
                object obj = ResourceManager.GetObject("OptionsPanelPath.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool OptionsPanelPath_Visible {
            get {
                object obj = ResourceManager.GetObject("OptionsPanelPath.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles OptionsSplitContainer_Anchor {
            get {
                object obj = ResourceManager.GetObject("OptionsSplitContainer.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool OptionsSplitContainer_IsSplitterFixed {
            get {
                object obj = ResourceManager.GetObject("OptionsSplitContainer.IsSplitterFixed", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=37}.
        /// </summary>
        public static System.Drawing.Point OptionsSplitContainer_Location {
            get {
                object obj = ResourceManager.GetObject("OptionsSplitContainer.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=0,Top=0,Right=0,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding OptionsSplitContainer_Margin {
            get {
                object obj = ResourceManager.GetObject("OptionsSplitContainer.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=340, Height=288}.
        /// </summary>
        public static System.Drawing.Size OptionsSplitContainer_MinimumSize {
            get {
                object obj = ResourceManager.GetObject("OptionsSplitContainer.MinimumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Orientation similar to Horizontal.
        /// </summary>
        public static System.Windows.Forms.Orientation OptionsSplitContainer_Orientation {
            get {
                object obj = ResourceManager.GetObject("OptionsSplitContainer.Orientation", resourceCulture);
                return ((System.Windows.Forms.Orientation)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 215.
        /// </summary>
        public static int OptionsSplitContainer_Panel1MinSize {
            get {
                object obj = ResourceManager.GetObject("OptionsSplitContainer.Panel1MinSize", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 64.
        /// </summary>
        public static int OptionsSplitContainer_Panel2MinSize {
            get {
                object obj = ResourceManager.GetObject("OptionsSplitContainer.Panel2MinSize", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=340, Height=292}.
        /// </summary>
        public static System.Drawing.Size OptionsSplitContainer_Size {
            get {
                object obj = ResourceManager.GetObject("OptionsSplitContainer.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 215.
        /// </summary>
        public static int OptionsSplitContainer_SplitterDistance {
            get {
                object obj = ResourceManager.GetObject("OptionsSplitContainer.SplitterDistance", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 8.
        /// </summary>
        public static int OptionsSplitContainer_SplitterWidth {
            get {
                object obj = ResourceManager.GetObject("OptionsSplitContainer.SplitterWidth", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        public static int OptionsSplitContainer_TabIndex {
            get {
                object obj = ResourceManager.GetObject("OptionsSplitContainer.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
